/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables;


import com.skan.farm.domain.JNaiveItFarm;
import com.skan.farm.domain.Keys;
import com.skan.farm.domain.tables.records.JAddressDetailRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JAddressDetail extends TableImpl<JAddressDetailRecord> {

    private static final long serialVersionUID = -1425100162;

    /**
     * The reference instance of <code>naive-it-farm.address_detail</code>
     */
    public static final JAddressDetail ADDRESS_DETAIL = new JAddressDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JAddressDetailRecord> getRecordType() {
        return JAddressDetailRecord.class;
    }

    /**
     * The column <code>naive-it-farm.address_detail.management_number</code>. 관리 번호
     */
    public final TableField<JAddressDetailRecord, Long> MANAGEMENT_NUMBER = createField(DSL.name("management_number"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "관리 번호");

    /**
     * The column <code>naive-it-farm.address_detail.hm_ad_no</code>.
     */
    public final TableField<JAddressDetailRecord, Long> HM_AD_NO = createField(DSL.name("hm_ad_no"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>naive-it-farm.address_detail.hm_type</code>.
     */
    public final TableField<JAddressDetailRecord, String> HM_TYPE = createField(DSL.name("hm_type"), org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>naive-it-farm.address_detail.hm_add_info</code>.
     */
    public final TableField<JAddressDetailRecord, String> HM_ADD_INFO = createField(DSL.name("hm_add_info"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>naive-it-farm.address_detail.user_id</code>. 사용자 아이디
     */
    public final TableField<JAddressDetailRecord, String> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "사용자 아이디");

    /**
     * Create a <code>naive-it-farm.address_detail</code> table reference
     */
    public JAddressDetail() {
        this(DSL.name("address_detail"), null);
    }

    /**
     * Create an aliased <code>naive-it-farm.address_detail</code> table reference
     */
    public JAddressDetail(String alias) {
        this(DSL.name(alias), ADDRESS_DETAIL);
    }

    /**
     * Create an aliased <code>naive-it-farm.address_detail</code> table reference
     */
    public JAddressDetail(Name alias) {
        this(alias, ADDRESS_DETAIL);
    }

    private JAddressDetail(Name alias, Table<JAddressDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private JAddressDetail(Name alias, Table<JAddressDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> JAddressDetail(Table<O> child, ForeignKey<O, JAddressDetailRecord> key) {
        super(child, key, ADDRESS_DETAIL);
    }

    @Override
    public Schema getSchema() {
        return JNaiveItFarm.NAIVE_IT_FARM;
    }

    @Override
    public UniqueKey<JAddressDetailRecord> getPrimaryKey() {
        return Keys.KEY_ADDRESS_DETAIL_PRIMARY;
    }

    @Override
    public List<UniqueKey<JAddressDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<JAddressDetailRecord>>asList(Keys.KEY_ADDRESS_DETAIL_PRIMARY);
    }

    @Override
    public JAddressDetail as(String alias) {
        return new JAddressDetail(DSL.name(alias), this);
    }

    @Override
    public JAddressDetail as(Name alias) {
        return new JAddressDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JAddressDetail rename(String name) {
        return new JAddressDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JAddressDetail rename(Name name) {
        return new JAddressDetail(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
