/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables;


import com.skan.farm.domain.JNaiveItFarm;
import com.skan.farm.domain.Keys;
import com.skan.farm.domain.tables.records.JEmailRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JEmail extends TableImpl<JEmailRecord> {

    private static final long serialVersionUID = 328290839;

    /**
     * The reference instance of <code>naive-it-farm.email</code>
     */
    public static final JEmail EMAIL = new JEmail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JEmailRecord> getRecordType() {
        return JEmailRecord.class;
    }

    /**
     * The column <code>naive-it-farm.email.management_number</code>. 관리 번호
     */
    public final TableField<JEmailRecord, Long> MANAGEMENT_NUMBER = createField(DSL.name("management_number"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "관리 번호");

    /**
     * The column <code>naive-it-farm.email.hm_em_no</code>.
     */
    public final TableField<JEmailRecord, Long> HM_EM_NO = createField(DSL.name("hm_em_no"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>naive-it-farm.email.hm_email</code>.
     */
    public final TableField<JEmailRecord, String> HM_EMAIL = createField(DSL.name("hm_email"), org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>naive-it-farm.email.user_id</code>. 사용자 아이디
     */
    public final TableField<JEmailRecord, String> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "사용자 아이디");

    /**
     * Create a <code>naive-it-farm.email</code> table reference
     */
    public JEmail() {
        this(DSL.name("email"), null);
    }

    /**
     * Create an aliased <code>naive-it-farm.email</code> table reference
     */
    public JEmail(String alias) {
        this(DSL.name(alias), EMAIL);
    }

    /**
     * Create an aliased <code>naive-it-farm.email</code> table reference
     */
    public JEmail(Name alias) {
        this(alias, EMAIL);
    }

    private JEmail(Name alias, Table<JEmailRecord> aliased) {
        this(alias, aliased, null);
    }

    private JEmail(Name alias, Table<JEmailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> JEmail(Table<O> child, ForeignKey<O, JEmailRecord> key) {
        super(child, key, EMAIL);
    }

    @Override
    public Schema getSchema() {
        return JNaiveItFarm.NAIVE_IT_FARM;
    }

    @Override
    public UniqueKey<JEmailRecord> getPrimaryKey() {
        return Keys.KEY_EMAIL_PRIMARY;
    }

    @Override
    public List<UniqueKey<JEmailRecord>> getKeys() {
        return Arrays.<UniqueKey<JEmailRecord>>asList(Keys.KEY_EMAIL_PRIMARY);
    }

    @Override
    public JEmail as(String alias) {
        return new JEmail(DSL.name(alias), this);
    }

    @Override
    public JEmail as(Name alias) {
        return new JEmail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JEmail rename(String name) {
        return new JEmail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JEmail rename(Name name) {
        return new JEmail(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
