package com.skan.farm.domain.entity;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

/**
 * 주소 상세 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Getter@Setter
public class AddressDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 주소록 관리. */
	private AddressManagement addressManagement;

	/** 순번. */
	private Long hmAdNo;

	/** 구분. */
	private String hmType;

	/** 주소정보. */
	private String hmAddInfo;



}
