/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JAddressManagement;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JAddressManagementRecord extends UpdatableRecordImpl<JAddressManagementRecord> implements Record4<String, Long, String, String> {

    private static final long serialVersionUID = -1613114873;

    /**
     * Setter for <code>naive-it-farm.address_management.user_id</code>. 사용자 아이디
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.address_management.user_id</code>. 사용자 아이디
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.address_management.management_number</code>. 관리 번호
     */
    public void setManagementNumber(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.address_management.management_number</code>. 관리 번호
     */
    public Long getManagementNumber() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.address_management.user_name</code>. 주소록 사용자 이름
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.address_management.user_name</code>. 주소록 사용자 이름
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.address_management.memo</code>. 메모
     */
    public void setMemo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.address_management.memo</code>. 메모
     */
    public String getMemo() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Long, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, Long, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JAddressManagement.ADDRESS_MANAGEMENT.USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return JAddressManagement.ADDRESS_MANAGEMENT.MANAGEMENT_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return JAddressManagement.ADDRESS_MANAGEMENT.USER_NAME;
    }

    @Override
    public Field<String> field4() {
        return JAddressManagement.ADDRESS_MANAGEMENT.MEMO;
    }

    @Override
    public String component1() {
        return getUserId();
    }

    @Override
    public Long component2() {
        return getManagementNumber();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public String component4() {
        return getMemo();
    }

    @Override
    public String value1() {
        return getUserId();
    }

    @Override
    public Long value2() {
        return getManagementNumber();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public String value4() {
        return getMemo();
    }

    @Override
    public JAddressManagementRecord value1(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public JAddressManagementRecord value2(Long value) {
        setManagementNumber(value);
        return this;
    }

    @Override
    public JAddressManagementRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public JAddressManagementRecord value4(String value) {
        setMemo(value);
        return this;
    }

    @Override
    public JAddressManagementRecord values(String value1, Long value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JAddressManagementRecord
     */
    public JAddressManagementRecord() {
        super(JAddressManagement.ADDRESS_MANAGEMENT);
    }

    /**
     * Create a detached, initialised JAddressManagementRecord
     */
    public JAddressManagementRecord(String userId, Long managementNumber, String userName, String memo) {
        super(JAddressManagement.ADDRESS_MANAGEMENT);

        set(0, userId);
        set(1, managementNumber);
        set(2, userName);
        set(3, memo);
    }
}
