/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JCalvesManagement;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Record3;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCalvesManagementRecord extends UpdatableRecordImpl<JCalvesManagementRecord> implements Record12<String, String, Short, LocalDateTime, String, String, LocalDateTime, LocalDateTime, Short, String, Long, String> {

    private static final long serialVersionUID = 544974407;

    /**
     * Setter for <code>naive-it-farm.calves_management.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.seq</code>.
     */
    public void setSeq(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.seq</code>.
     */
    public Short getSeq() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.calving_date</code>.
     */
    public void setCalvingDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.calving_date</code>.
     */
    public LocalDateTime getCalvingDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.entity_identification_number_child</code>.
     */
    public void setEntityIdentificationNumberChild(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.entity_identification_number_child</code>.
     */
    public String getEntityIdentificationNumberChild() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.entity_management_number_child</code>.
     */
    public void setEntityManagementNumberChild(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.entity_management_number_child</code>.
     */
    public String getEntityManagementNumberChild() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.expected_date_confinement</code>.
     */
    public void setExpectedDateConfinement(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.expected_date_confinement</code>.
     */
    public LocalDateTime getExpectedDateConfinement() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.fertilization_date</code>.
     */
    public void setFertilizationDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.fertilization_date</code>.
     */
    public LocalDateTime getFertilizationDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.fertilization_index</code>.
     */
    public void setFertilizationIndex(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.fertilization_index</code>.
     */
    public Short getFertilizationIndex() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.nothing_special</code>.
     */
    public void setNothingSpecial(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.nothing_special</code>.
     */
    public String getNothingSpecial() {
        return (String) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.sperm_no</code>.
     */
    public void setSpermNo(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.sperm_no</code>.
     */
    public Long getSpermNo() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>naive-it-farm.calves_management.years</code>.
     */
    public void setYears(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>naive-it-farm.calves_management.years</code>.
     */
    public String getYears() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, Short> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, String, Short, LocalDateTime, String, String, LocalDateTime, LocalDateTime, Short, String, Long, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, String, Short, LocalDateTime, String, String, LocalDateTime, LocalDateTime, Short, String, Long, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JCalvesManagement.CALVES_MANAGEMENT.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field2() {
        return JCalvesManagement.CALVES_MANAGEMENT.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<Short> field3() {
        return JCalvesManagement.CALVES_MANAGEMENT.SEQ;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return JCalvesManagement.CALVES_MANAGEMENT.CALVING_DATE;
    }

    @Override
    public Field<String> field5() {
        return JCalvesManagement.CALVES_MANAGEMENT.ENTITY_IDENTIFICATION_NUMBER_CHILD;
    }

    @Override
    public Field<String> field6() {
        return JCalvesManagement.CALVES_MANAGEMENT.ENTITY_MANAGEMENT_NUMBER_CHILD;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JCalvesManagement.CALVES_MANAGEMENT.EXPECTED_DATE_CONFINEMENT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JCalvesManagement.CALVES_MANAGEMENT.FERTILIZATION_DATE;
    }

    @Override
    public Field<Short> field9() {
        return JCalvesManagement.CALVES_MANAGEMENT.FERTILIZATION_INDEX;
    }

    @Override
    public Field<String> field10() {
        return JCalvesManagement.CALVES_MANAGEMENT.NOTHING_SPECIAL;
    }

    @Override
    public Field<Long> field11() {
        return JCalvesManagement.CALVES_MANAGEMENT.SPERM_NO;
    }

    @Override
    public Field<String> field12() {
        return JCalvesManagement.CALVES_MANAGEMENT.YEARS;
    }

    @Override
    public String component1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component2() {
        return getEntityManagementNumber();
    }

    @Override
    public Short component3() {
        return getSeq();
    }

    @Override
    public LocalDateTime component4() {
        return getCalvingDate();
    }

    @Override
    public String component5() {
        return getEntityIdentificationNumberChild();
    }

    @Override
    public String component6() {
        return getEntityManagementNumberChild();
    }

    @Override
    public LocalDateTime component7() {
        return getExpectedDateConfinement();
    }

    @Override
    public LocalDateTime component8() {
        return getFertilizationDate();
    }

    @Override
    public Short component9() {
        return getFertilizationIndex();
    }

    @Override
    public String component10() {
        return getNothingSpecial();
    }

    @Override
    public Long component11() {
        return getSpermNo();
    }

    @Override
    public String component12() {
        return getYears();
    }

    @Override
    public String value1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value2() {
        return getEntityManagementNumber();
    }

    @Override
    public Short value3() {
        return getSeq();
    }

    @Override
    public LocalDateTime value4() {
        return getCalvingDate();
    }

    @Override
    public String value5() {
        return getEntityIdentificationNumberChild();
    }

    @Override
    public String value6() {
        return getEntityManagementNumberChild();
    }

    @Override
    public LocalDateTime value7() {
        return getExpectedDateConfinement();
    }

    @Override
    public LocalDateTime value8() {
        return getFertilizationDate();
    }

    @Override
    public Short value9() {
        return getFertilizationIndex();
    }

    @Override
    public String value10() {
        return getNothingSpecial();
    }

    @Override
    public Long value11() {
        return getSpermNo();
    }

    @Override
    public String value12() {
        return getYears();
    }

    @Override
    public JCalvesManagementRecord value1(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value2(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value3(Short value) {
        setSeq(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value4(LocalDateTime value) {
        setCalvingDate(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value5(String value) {
        setEntityIdentificationNumberChild(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value6(String value) {
        setEntityManagementNumberChild(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value7(LocalDateTime value) {
        setExpectedDateConfinement(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value8(LocalDateTime value) {
        setFertilizationDate(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value9(Short value) {
        setFertilizationIndex(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value10(String value) {
        setNothingSpecial(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value11(Long value) {
        setSpermNo(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord value12(String value) {
        setYears(value);
        return this;
    }

    @Override
    public JCalvesManagementRecord values(String value1, String value2, Short value3, LocalDateTime value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8, Short value9, String value10, Long value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JCalvesManagementRecord
     */
    public JCalvesManagementRecord() {
        super(JCalvesManagement.CALVES_MANAGEMENT);
    }

    /**
     * Create a detached, initialised JCalvesManagementRecord
     */
    public JCalvesManagementRecord(String entityIdentificationNumber, String entityManagementNumber, Short seq, LocalDateTime calvingDate, String entityIdentificationNumberChild, String entityManagementNumberChild, LocalDateTime expectedDateConfinement, LocalDateTime fertilizationDate, Short fertilizationIndex, String nothingSpecial, Long spermNo, String years) {
        super(JCalvesManagement.CALVES_MANAGEMENT);

        set(0, entityIdentificationNumber);
        set(1, entityManagementNumber);
        set(2, seq);
        set(3, calvingDate);
        set(4, entityIdentificationNumberChild);
        set(5, entityManagementNumberChild);
        set(6, expectedDateConfinement);
        set(7, fertilizationDate);
        set(8, fertilizationIndex);
        set(9, nothingSpecial);
        set(10, spermNo);
        set(11, years);
    }
}
