/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JCattleSellStoreInformation;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCattleSellStoreInformationRecord extends UpdatableRecordImpl<JCattleSellStoreInformationRecord> implements Record10<String, String, String, Short, Short, LocalDate, String, String, Integer, String> {

    private static final long serialVersionUID = 960170472;

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.beef_grade</code>.
     */
    public void setBeefGrade(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.beef_grade</code>.
     */
    public String getBeefGrade() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.dressed_weight</code>.
     */
    public void setDressedWeight(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.dressed_weight</code>.
     */
    public Short getDressedWeight() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.liveweight</code>.
     */
    public void setLiveweight(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.liveweight</code>.
     */
    public Short getLiveweight() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.sell_date</code>.
     */
    public void setSellDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.sell_date</code>.
     */
    public LocalDate getSellDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.sell_note</code>.
     */
    public void setSellNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.sell_note</code>.
     */
    public String getSellNote() {
        return (String) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.sell_phone_number</code>.
     */
    public void setSellPhoneNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.sell_phone_number</code>.
     */
    public String getSellPhoneNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.selling_price</code>.
     */
    public void setSellingPrice(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.selling_price</code>.
     */
    public Integer getSellingPrice() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.cattle_sell_store_information.store_name</code>.
     */
    public void setStoreName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.cattle_sell_store_information.store_name</code>.
     */
    public String getStoreName() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, String, Short, Short, LocalDate, String, String, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, String, Short, Short, LocalDate, String, String, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field2() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.BEEF_GRADE;
    }

    @Override
    public Field<Short> field4() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.DRESSED_WEIGHT;
    }

    @Override
    public Field<Short> field5() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.LIVEWEIGHT;
    }

    @Override
    public Field<LocalDate> field6() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.SELL_DATE;
    }

    @Override
    public Field<String> field7() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.SELL_NOTE;
    }

    @Override
    public Field<String> field8() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.SELL_PHONE_NUMBER;
    }

    @Override
    public Field<Integer> field9() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.SELLING_PRICE;
    }

    @Override
    public Field<String> field10() {
        return JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.STORE_NAME;
    }

    @Override
    public String component1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component2() {
        return getEntityManagementNumber();
    }

    @Override
    public String component3() {
        return getBeefGrade();
    }

    @Override
    public Short component4() {
        return getDressedWeight();
    }

    @Override
    public Short component5() {
        return getLiveweight();
    }

    @Override
    public LocalDate component6() {
        return getSellDate();
    }

    @Override
    public String component7() {
        return getSellNote();
    }

    @Override
    public String component8() {
        return getSellPhoneNumber();
    }

    @Override
    public Integer component9() {
        return getSellingPrice();
    }

    @Override
    public String component10() {
        return getStoreName();
    }

    @Override
    public String value1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value2() {
        return getEntityManagementNumber();
    }

    @Override
    public String value3() {
        return getBeefGrade();
    }

    @Override
    public Short value4() {
        return getDressedWeight();
    }

    @Override
    public Short value5() {
        return getLiveweight();
    }

    @Override
    public LocalDate value6() {
        return getSellDate();
    }

    @Override
    public String value7() {
        return getSellNote();
    }

    @Override
    public String value8() {
        return getSellPhoneNumber();
    }

    @Override
    public Integer value9() {
        return getSellingPrice();
    }

    @Override
    public String value10() {
        return getStoreName();
    }

    @Override
    public JCattleSellStoreInformationRecord value1(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value2(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value3(String value) {
        setBeefGrade(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value4(Short value) {
        setDressedWeight(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value5(Short value) {
        setLiveweight(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value6(LocalDate value) {
        setSellDate(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value7(String value) {
        setSellNote(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value8(String value) {
        setSellPhoneNumber(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value9(Integer value) {
        setSellingPrice(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord value10(String value) {
        setStoreName(value);
        return this;
    }

    @Override
    public JCattleSellStoreInformationRecord values(String value1, String value2, String value3, Short value4, Short value5, LocalDate value6, String value7, String value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JCattleSellStoreInformationRecord
     */
    public JCattleSellStoreInformationRecord() {
        super(JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION);
    }

    /**
     * Create a detached, initialised JCattleSellStoreInformationRecord
     */
    public JCattleSellStoreInformationRecord(String entityIdentificationNumber, String entityManagementNumber, String beefGrade, Short dressedWeight, Short liveweight, LocalDate sellDate, String sellNote, String sellPhoneNumber, Integer sellingPrice, String storeName) {
        super(JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION);

        set(0, entityIdentificationNumber);
        set(1, entityManagementNumber);
        set(2, beefGrade);
        set(3, dressedWeight);
        set(4, liveweight);
        set(5, sellDate);
        set(6, sellNote);
        set(7, sellPhoneNumber);
        set(8, sellingPrice);
        set(9, storeName);
    }
}
