/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JCommonCode;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCommonCodeRecord extends UpdatableRecordImpl<JCommonCodeRecord> implements Record6<String, String, Long, String, String, LocalDateTime> {

    private static final long serialVersionUID = -1778853203;

    /**
     * Setter for <code>naive-it-farm.common_code.code</code>. 코드
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.common_code.code</code>. 코드
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.common_code.upper_code</code>. 상위코드
     */
    public void setUpperCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.common_code.upper_code</code>. 상위코드
     */
    public String getUpperCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.common_code.code_seq</code>. 그룹별 코드 순번
     */
    public void setCodeSeq(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.common_code.code_seq</code>. 그룹별 코드 순번
     */
    public Long getCodeSeq() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.common_code.code_name</code>. 코드이름
     */
    public void setCodeName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.common_code.code_name</code>. 코드이름
     */
    public String getCodeName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.common_code.code_comment</code>. 코드 설명
     */
    public void setCodeComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.common_code.code_comment</code>. 코드 설명
     */
    public String getCodeComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.common_code.created_time</code>. 생성일시
     */
    public void setCreatedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.common_code.created_time</code>. 생성일시
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, Long, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, Long, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JCommonCode.COMMON_CODE.CODE;
    }

    @Override
    public Field<String> field2() {
        return JCommonCode.COMMON_CODE.UPPER_CODE;
    }

    @Override
    public Field<Long> field3() {
        return JCommonCode.COMMON_CODE.CODE_SEQ;
    }

    @Override
    public Field<String> field4() {
        return JCommonCode.COMMON_CODE.CODE_NAME;
    }

    @Override
    public Field<String> field5() {
        return JCommonCode.COMMON_CODE.CODE_COMMENT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return JCommonCode.COMMON_CODE.CREATED_TIME;
    }

    @Override
    public String component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getUpperCode();
    }

    @Override
    public Long component3() {
        return getCodeSeq();
    }

    @Override
    public String component4() {
        return getCodeName();
    }

    @Override
    public String component5() {
        return getCodeComment();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedTime();
    }

    @Override
    public String value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getUpperCode();
    }

    @Override
    public Long value3() {
        return getCodeSeq();
    }

    @Override
    public String value4() {
        return getCodeName();
    }

    @Override
    public String value5() {
        return getCodeComment();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedTime();
    }

    @Override
    public JCommonCodeRecord value1(String value) {
        setCode(value);
        return this;
    }

    @Override
    public JCommonCodeRecord value2(String value) {
        setUpperCode(value);
        return this;
    }

    @Override
    public JCommonCodeRecord value3(Long value) {
        setCodeSeq(value);
        return this;
    }

    @Override
    public JCommonCodeRecord value4(String value) {
        setCodeName(value);
        return this;
    }

    @Override
    public JCommonCodeRecord value5(String value) {
        setCodeComment(value);
        return this;
    }

    @Override
    public JCommonCodeRecord value6(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JCommonCodeRecord values(String value1, String value2, Long value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JCommonCodeRecord
     */
    public JCommonCodeRecord() {
        super(JCommonCode.COMMON_CODE);
    }

    /**
     * Create a detached, initialised JCommonCodeRecord
     */
    public JCommonCodeRecord(String code, String upperCode, Long codeSeq, String codeName, String codeComment, LocalDateTime createdTime) {
        super(JCommonCode.COMMON_CODE);

        set(0, code);
        set(1, upperCode);
        set(2, codeSeq);
        set(3, codeName);
        set(4, codeComment);
        set(5, createdTime);
    }
}
