/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JDiary;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDiaryRecord extends UpdatableRecordImpl<JDiaryRecord> implements Record15<String, LocalDateTime, String, Short, String, Short, LocalDateTime, String, Short, LocalDate, String, String, String, String, String> {

    private static final long serialVersionUID = 329417648;

    /**
     * Setter for <code>naive-it-farm.diary.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.diary.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.diary.max_temperature_type</code>.
     */
    public void setMaxTemperatureType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.max_temperature_type</code>.
     */
    public String getMaxTemperatureType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.diary.maximum_temperature</code>.
     */
    public void setMaximumTemperature(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.maximum_temperature</code>.
     */
    public Short getMaximumTemperature() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.diary.min_temperature_type</code>.
     */
    public void setMinTemperatureType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.min_temperature_type</code>.
     */
    public String getMinTemperatureType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.diary.minimum_temperature</code>.
     */
    public void setMinimumTemperature(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.minimum_temperature</code>.
     */
    public Short getMinimumTemperature() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.diary.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.diary.public_yn</code>.
     */
    public void setPublicYn(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.public_yn</code>.
     */
    public String getPublicYn() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.diary.seq</code>.
     */
    public void setSeq(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.seq</code>.
     */
    public Short getSeq() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.diary.standard_date</code>.
     */
    public void setStandardDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.standard_date</code>.
     */
    public LocalDate getStandardDate() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.diary.subject</code>.
     */
    public void setSubject(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.subject</code>.
     */
    public String getSubject() {
        return (String) get(10);
    }

    /**
     * Setter for <code>naive-it-farm.diary.today_content</code>.
     */
    public void setTodayContent(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.today_content</code>.
     */
    public String getTodayContent() {
        return (String) get(11);
    }

    /**
     * Setter for <code>naive-it-farm.diary.today_weather_code</code>.
     */
    public void setTodayWeatherCode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.today_weather_code</code>.
     */
    public String getTodayWeatherCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>naive-it-farm.diary.tomorrow_todo</code>.
     */
    public void setTomorrowTodo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.tomorrow_todo</code>.
     */
    public String getTomorrowTodo() {
        return (String) get(13);
    }

    /**
     * Setter for <code>naive-it-farm.diary.user_id</code>.
     */
    public void setUserId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>naive-it-farm.diary.user_id</code>.
     */
    public String getUserId() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, LocalDateTime, String, Short, String, Short, LocalDateTime, String, Short, LocalDate, String, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, LocalDateTime, String, Short, String, Short, LocalDateTime, String, Short, LocalDate, String, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JDiary.DIARY.UUID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return JDiary.DIARY.CREATED_TIME;
    }

    @Override
    public Field<String> field3() {
        return JDiary.DIARY.MAX_TEMPERATURE_TYPE;
    }

    @Override
    public Field<Short> field4() {
        return JDiary.DIARY.MAXIMUM_TEMPERATURE;
    }

    @Override
    public Field<String> field5() {
        return JDiary.DIARY.MIN_TEMPERATURE_TYPE;
    }

    @Override
    public Field<Short> field6() {
        return JDiary.DIARY.MINIMUM_TEMPERATURE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JDiary.DIARY.MODIFIED_TIME;
    }

    @Override
    public Field<String> field8() {
        return JDiary.DIARY.PUBLIC_YN;
    }

    @Override
    public Field<Short> field9() {
        return JDiary.DIARY.SEQ;
    }

    @Override
    public Field<LocalDate> field10() {
        return JDiary.DIARY.STANDARD_DATE;
    }

    @Override
    public Field<String> field11() {
        return JDiary.DIARY.SUBJECT;
    }

    @Override
    public Field<String> field12() {
        return JDiary.DIARY.TODAY_CONTENT;
    }

    @Override
    public Field<String> field13() {
        return JDiary.DIARY.TODAY_WEATHER_CODE;
    }

    @Override
    public Field<String> field14() {
        return JDiary.DIARY.TOMORROW_TODO;
    }

    @Override
    public Field<String> field15() {
        return JDiary.DIARY.USER_ID;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedTime();
    }

    @Override
    public String component3() {
        return getMaxTemperatureType();
    }

    @Override
    public Short component4() {
        return getMaximumTemperature();
    }

    @Override
    public String component5() {
        return getMinTemperatureType();
    }

    @Override
    public Short component6() {
        return getMinimumTemperature();
    }

    @Override
    public LocalDateTime component7() {
        return getModifiedTime();
    }

    @Override
    public String component8() {
        return getPublicYn();
    }

    @Override
    public Short component9() {
        return getSeq();
    }

    @Override
    public LocalDate component10() {
        return getStandardDate();
    }

    @Override
    public String component11() {
        return getSubject();
    }

    @Override
    public String component12() {
        return getTodayContent();
    }

    @Override
    public String component13() {
        return getTodayWeatherCode();
    }

    @Override
    public String component14() {
        return getTomorrowTodo();
    }

    @Override
    public String component15() {
        return getUserId();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedTime();
    }

    @Override
    public String value3() {
        return getMaxTemperatureType();
    }

    @Override
    public Short value4() {
        return getMaximumTemperature();
    }

    @Override
    public String value5() {
        return getMinTemperatureType();
    }

    @Override
    public Short value6() {
        return getMinimumTemperature();
    }

    @Override
    public LocalDateTime value7() {
        return getModifiedTime();
    }

    @Override
    public String value8() {
        return getPublicYn();
    }

    @Override
    public Short value9() {
        return getSeq();
    }

    @Override
    public LocalDate value10() {
        return getStandardDate();
    }

    @Override
    public String value11() {
        return getSubject();
    }

    @Override
    public String value12() {
        return getTodayContent();
    }

    @Override
    public String value13() {
        return getTodayWeatherCode();
    }

    @Override
    public String value14() {
        return getTomorrowTodo();
    }

    @Override
    public String value15() {
        return getUserId();
    }

    @Override
    public JDiaryRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public JDiaryRecord value2(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JDiaryRecord value3(String value) {
        setMaxTemperatureType(value);
        return this;
    }

    @Override
    public JDiaryRecord value4(Short value) {
        setMaximumTemperature(value);
        return this;
    }

    @Override
    public JDiaryRecord value5(String value) {
        setMinTemperatureType(value);
        return this;
    }

    @Override
    public JDiaryRecord value6(Short value) {
        setMinimumTemperature(value);
        return this;
    }

    @Override
    public JDiaryRecord value7(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public JDiaryRecord value8(String value) {
        setPublicYn(value);
        return this;
    }

    @Override
    public JDiaryRecord value9(Short value) {
        setSeq(value);
        return this;
    }

    @Override
    public JDiaryRecord value10(LocalDate value) {
        setStandardDate(value);
        return this;
    }

    @Override
    public JDiaryRecord value11(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public JDiaryRecord value12(String value) {
        setTodayContent(value);
        return this;
    }

    @Override
    public JDiaryRecord value13(String value) {
        setTodayWeatherCode(value);
        return this;
    }

    @Override
    public JDiaryRecord value14(String value) {
        setTomorrowTodo(value);
        return this;
    }

    @Override
    public JDiaryRecord value15(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public JDiaryRecord values(String value1, LocalDateTime value2, String value3, Short value4, String value5, Short value6, LocalDateTime value7, String value8, Short value9, LocalDate value10, String value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDiaryRecord
     */
    public JDiaryRecord() {
        super(JDiary.DIARY);
    }

    /**
     * Create a detached, initialised JDiaryRecord
     */
    public JDiaryRecord(String uuid, LocalDateTime createdTime, String maxTemperatureType, Short maximumTemperature, String minTemperatureType, Short minimumTemperature, LocalDateTime modifiedTime, String publicYn, Short seq, LocalDate standardDate, String subject, String todayContent, String todayWeatherCode, String tomorrowTodo, String userId) {
        super(JDiary.DIARY);

        set(0, uuid);
        set(1, createdTime);
        set(2, maxTemperatureType);
        set(3, maximumTemperature);
        set(4, minTemperatureType);
        set(5, minimumTemperature);
        set(6, modifiedTime);
        set(7, publicYn);
        set(8, seq);
        set(9, standardDate);
        set(10, subject);
        set(11, todayContent);
        set(12, todayWeatherCode);
        set(13, tomorrowTodo);
        set(14, userId);
    }
}
