/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JDiseaseTreatment;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record3;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDiseaseTreatmentRecord extends UpdatableRecordImpl<JDiseaseTreatmentRecord> implements Record11<LocalDate, String, String, LocalDateTime, Short, LocalDate, String, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 791988163;

    /**
     * Setter for <code>naive-it-farm.disease_treatment.day</code>.
     */
    public void setDay(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.day</code>.
     */
    public LocalDate getDay() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.cure_age_of_month</code>.
     */
    public void setCureAgeOfMonth(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.cure_age_of_month</code>.
     */
    public Short getCureAgeOfMonth() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.cure_date</code>.
     */
    public void setCureDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.cure_date</code>.
     */
    public LocalDate getCureDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.disease_name</code>.
     */
    public void setDiseaseName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.disease_name</code>.
     */
    public String getDiseaseName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.remark</code>.
     */
    public void setRemark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.remark</code>.
     */
    public String getRemark() {
        return (String) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.symptom</code>.
     */
    public void setSymptom(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.symptom</code>.
     */
    public String getSymptom() {
        return (String) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.treatment_details</code>.
     */
    public void setTreatmentDetails(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.treatment_details</code>.
     */
    public String getTreatmentDetails() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<LocalDate, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<LocalDate, String, String, LocalDateTime, Short, LocalDate, String, LocalDateTime, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<LocalDate, String, String, LocalDateTime, Short, LocalDate, String, LocalDateTime, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<LocalDate> field1() {
        return JDiseaseTreatment.DISEASE_TREATMENT.DAY;
    }

    @Override
    public Field<String> field2() {
        return JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return JDiseaseTreatment.DISEASE_TREATMENT.CREATED_TIME;
    }

    @Override
    public Field<Short> field5() {
        return JDiseaseTreatment.DISEASE_TREATMENT.CURE_AGE_OF_MONTH;
    }

    @Override
    public Field<LocalDate> field6() {
        return JDiseaseTreatment.DISEASE_TREATMENT.CURE_DATE;
    }

    @Override
    public Field<String> field7() {
        return JDiseaseTreatment.DISEASE_TREATMENT.DISEASE_NAME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JDiseaseTreatment.DISEASE_TREATMENT.MODIFIED_TIME;
    }

    @Override
    public Field<String> field9() {
        return JDiseaseTreatment.DISEASE_TREATMENT.REMARK;
    }

    @Override
    public Field<String> field10() {
        return JDiseaseTreatment.DISEASE_TREATMENT.SYMPTOM;
    }

    @Override
    public Field<String> field11() {
        return JDiseaseTreatment.DISEASE_TREATMENT.TREATMENT_DETAILS;
    }

    @Override
    public LocalDate component1() {
        return getDay();
    }

    @Override
    public String component2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component3() {
        return getEntityManagementNumber();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedTime();
    }

    @Override
    public Short component5() {
        return getCureAgeOfMonth();
    }

    @Override
    public LocalDate component6() {
        return getCureDate();
    }

    @Override
    public String component7() {
        return getDiseaseName();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedTime();
    }

    @Override
    public String component9() {
        return getRemark();
    }

    @Override
    public String component10() {
        return getSymptom();
    }

    @Override
    public String component11() {
        return getTreatmentDetails();
    }

    @Override
    public LocalDate value1() {
        return getDay();
    }

    @Override
    public String value2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value3() {
        return getEntityManagementNumber();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedTime();
    }

    @Override
    public Short value5() {
        return getCureAgeOfMonth();
    }

    @Override
    public LocalDate value6() {
        return getCureDate();
    }

    @Override
    public String value7() {
        return getDiseaseName();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedTime();
    }

    @Override
    public String value9() {
        return getRemark();
    }

    @Override
    public String value10() {
        return getSymptom();
    }

    @Override
    public String value11() {
        return getTreatmentDetails();
    }

    @Override
    public JDiseaseTreatmentRecord value1(LocalDate value) {
        setDay(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value2(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value3(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value4(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value5(Short value) {
        setCureAgeOfMonth(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value6(LocalDate value) {
        setCureDate(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value7(String value) {
        setDiseaseName(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value8(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value9(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value10(String value) {
        setSymptom(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value11(String value) {
        setTreatmentDetails(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord values(LocalDate value1, String value2, String value3, LocalDateTime value4, Short value5, LocalDate value6, String value7, LocalDateTime value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDiseaseTreatmentRecord
     */
    public JDiseaseTreatmentRecord() {
        super(JDiseaseTreatment.DISEASE_TREATMENT);
    }

    /**
     * Create a detached, initialised JDiseaseTreatmentRecord
     */
    public JDiseaseTreatmentRecord(LocalDate day, String entityIdentificationNumber, String entityManagementNumber, LocalDateTime createdTime, Short cureAgeOfMonth, LocalDate cureDate, String diseaseName, LocalDateTime modifiedTime, String remark, String symptom, String treatmentDetails) {
        super(JDiseaseTreatment.DISEASE_TREATMENT);

        set(0, day);
        set(1, entityIdentificationNumber);
        set(2, entityManagementNumber);
        set(3, createdTime);
        set(4, cureAgeOfMonth);
        set(5, cureDate);
        set(6, diseaseName);
        set(7, modifiedTime);
        set(8, remark);
        set(9, symptom);
        set(10, treatmentDetails);
    }
}
