/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JDiseaseDetail;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record4;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDiseaseDetailRecord extends UpdatableRecordImpl<JDiseaseDetailRecord> implements Record10<LocalDate, String, String, Short, LocalDateTime, String, String, LocalDateTime, String, LocalDate> {

    private static final long serialVersionUID = 1303693465;

    /**
     * Setter for <code>naive-it-farm.disease_detail.day</code>.
     */
    public void setDay(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.day</code>.
     */
    public LocalDate getDay() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.seq</code>.
     */
    public void setSeq(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.seq</code>.
     */
    public Short getSeq() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.injection_method</code>.
     */
    public void setInjectionMethod(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.injection_method</code>.
     */
    public String getInjectionMethod() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.medication_name</code>.
     */
    public void setMedicationName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.medication_name</code>.
     */
    public String getMedicationName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.needle_lose_yn</code>.
     */
    public void setNeedleLoseYn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.needle_lose_yn</code>.
     */
    public String getNeedleLoseYn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.disease_detail.withdrawal_period_expiration_date</code>.
     */
    public void setWithdrawalPeriodExpirationDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_detail.withdrawal_period_expiration_date</code>.
     */
    public LocalDate getWithdrawalPeriodExpirationDate() {
        return (LocalDate) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<LocalDate, String, String, Short> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<LocalDate, String, String, Short, LocalDateTime, String, String, LocalDateTime, String, LocalDate> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<LocalDate, String, String, Short, LocalDateTime, String, String, LocalDateTime, String, LocalDate> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<LocalDate> field1() {
        return JDiseaseDetail.DISEASE_DETAIL.DAY;
    }

    @Override
    public Field<String> field2() {
        return JDiseaseDetail.DISEASE_DETAIL.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return JDiseaseDetail.DISEASE_DETAIL.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<Short> field4() {
        return JDiseaseDetail.DISEASE_DETAIL.SEQ;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JDiseaseDetail.DISEASE_DETAIL.CREATED_TIME;
    }

    @Override
    public Field<String> field6() {
        return JDiseaseDetail.DISEASE_DETAIL.INJECTION_METHOD;
    }

    @Override
    public Field<String> field7() {
        return JDiseaseDetail.DISEASE_DETAIL.MEDICATION_NAME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JDiseaseDetail.DISEASE_DETAIL.MODIFIED_TIME;
    }

    @Override
    public Field<String> field9() {
        return JDiseaseDetail.DISEASE_DETAIL.NEEDLE_LOSE_YN;
    }

    @Override
    public Field<LocalDate> field10() {
        return JDiseaseDetail.DISEASE_DETAIL.WITHDRAWAL_PERIOD_EXPIRATION_DATE;
    }

    @Override
    public LocalDate component1() {
        return getDay();
    }

    @Override
    public String component2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component3() {
        return getEntityManagementNumber();
    }

    @Override
    public Short component4() {
        return getSeq();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedTime();
    }

    @Override
    public String component6() {
        return getInjectionMethod();
    }

    @Override
    public String component7() {
        return getMedicationName();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedTime();
    }

    @Override
    public String component9() {
        return getNeedleLoseYn();
    }

    @Override
    public LocalDate component10() {
        return getWithdrawalPeriodExpirationDate();
    }

    @Override
    public LocalDate value1() {
        return getDay();
    }

    @Override
    public String value2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value3() {
        return getEntityManagementNumber();
    }

    @Override
    public Short value4() {
        return getSeq();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedTime();
    }

    @Override
    public String value6() {
        return getInjectionMethod();
    }

    @Override
    public String value7() {
        return getMedicationName();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedTime();
    }

    @Override
    public String value9() {
        return getNeedleLoseYn();
    }

    @Override
    public LocalDate value10() {
        return getWithdrawalPeriodExpirationDate();
    }

    @Override
    public JDiseaseDetailRecord value1(LocalDate value) {
        setDay(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value2(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value3(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value4(Short value) {
        setSeq(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value5(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value6(String value) {
        setInjectionMethod(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value7(String value) {
        setMedicationName(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value8(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value9(String value) {
        setNeedleLoseYn(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord value10(LocalDate value) {
        setWithdrawalPeriodExpirationDate(value);
        return this;
    }

    @Override
    public JDiseaseDetailRecord values(LocalDate value1, String value2, String value3, Short value4, LocalDateTime value5, String value6, String value7, LocalDateTime value8, String value9, LocalDate value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDiseaseDetailRecord
     */
    public JDiseaseDetailRecord() {
        super(JDiseaseDetail.DISEASE_DETAIL);
    }

    /**
     * Create a detached, initialised JDiseaseDetailRecord
     */
    public JDiseaseDetailRecord(LocalDate day, String entityIdentificationNumber, String entityManagementNumber, Short seq, LocalDateTime createdTime, String injectionMethod, String medicationName, LocalDateTime modifiedTime, String needleLoseYn, LocalDate withdrawalPeriodExpirationDate) {
        super(JDiseaseDetail.DISEASE_DETAIL);

        set(0, day);
        set(1, entityIdentificationNumber);
        set(2, entityManagementNumber);
        set(3, seq);
        set(4, createdTime);
        set(5, injectionMethod);
        set(6, medicationName);
        set(7, modifiedTime);
        set(8, needleLoseYn);
        set(9, withdrawalPeriodExpirationDate);
    }
}
