/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JDiseaseTreatment;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record3;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDiseaseTreatmentRecord extends UpdatableRecordImpl<JDiseaseTreatmentRecord> implements Record13<LocalDate, String, String, LocalDateTime, LocalDate, String, String, String, LocalDateTime, String, String, String, LocalDate> {

    private static final long serialVersionUID = -1060622953;

    /**
     * Setter for <code>naive-it-farm.disease_treatment.day</code>.
     */
    public void setDay(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.day</code>.
     */
    public LocalDate getDay() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.cure_date</code>.
     */
    public void setCureDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.cure_date</code>.
     */
    public LocalDate getCureDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.disease_name</code>.
     */
    public void setDiseaseName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.disease_name</code>.
     */
    public String getDiseaseName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.injection_method</code>.
     */
    public void setInjectionMethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.injection_method</code>.
     */
    public String getInjectionMethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.medication_name</code>.
     */
    public void setMedicationName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.medication_name</code>.
     */
    public String getMedicationName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.needle_lose_yn</code>.
     */
    public void setNeedleLoseYn(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.needle_lose_yn</code>.
     */
    public String getNeedleLoseYn() {
        return (String) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.remark</code>.
     */
    public void setRemark(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.remark</code>.
     */
    public String getRemark() {
        return (String) get(10);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.treatment_details</code>.
     */
    public void setTreatmentDetails(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.treatment_details</code>.
     */
    public String getTreatmentDetails() {
        return (String) get(11);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.withdrawal_period_expiration_date</code>.
     */
    public void setWithdrawalPeriodExpirationDate(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.withdrawal_period_expiration_date</code>.
     */
    public LocalDate getWithdrawalPeriodExpirationDate() {
        return (LocalDate) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<LocalDate, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<LocalDate, String, String, LocalDateTime, LocalDate, String, String, String, LocalDateTime, String, String, String, LocalDate> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<LocalDate, String, String, LocalDateTime, LocalDate, String, String, String, LocalDateTime, String, String, String, LocalDate> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<LocalDate> field1() {
        return JDiseaseTreatment.DISEASE_TREATMENT.DAY;
    }

    @Override
    public Field<String> field2() {
        return JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return JDiseaseTreatment.DISEASE_TREATMENT.CREATED_TIME;
    }

    @Override
    public Field<LocalDate> field5() {
        return JDiseaseTreatment.DISEASE_TREATMENT.CURE_DATE;
    }

    @Override
    public Field<String> field6() {
        return JDiseaseTreatment.DISEASE_TREATMENT.DISEASE_NAME;
    }

    @Override
    public Field<String> field7() {
        return JDiseaseTreatment.DISEASE_TREATMENT.INJECTION_METHOD;
    }

    @Override
    public Field<String> field8() {
        return JDiseaseTreatment.DISEASE_TREATMENT.MEDICATION_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JDiseaseTreatment.DISEASE_TREATMENT.MODIFIED_TIME;
    }

    @Override
    public Field<String> field10() {
        return JDiseaseTreatment.DISEASE_TREATMENT.NEEDLE_LOSE_YN;
    }

    @Override
    public Field<String> field11() {
        return JDiseaseTreatment.DISEASE_TREATMENT.REMARK;
    }

    @Override
    public Field<String> field12() {
        return JDiseaseTreatment.DISEASE_TREATMENT.TREATMENT_DETAILS;
    }

    @Override
    public Field<LocalDate> field13() {
        return JDiseaseTreatment.DISEASE_TREATMENT.WITHDRAWAL_PERIOD_EXPIRATION_DATE;
    }

    @Override
    public LocalDate component1() {
        return getDay();
    }

    @Override
    public String component2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component3() {
        return getEntityManagementNumber();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedTime();
    }

    @Override
    public LocalDate component5() {
        return getCureDate();
    }

    @Override
    public String component6() {
        return getDiseaseName();
    }

    @Override
    public String component7() {
        return getInjectionMethod();
    }

    @Override
    public String component8() {
        return getMedicationName();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedTime();
    }

    @Override
    public String component10() {
        return getNeedleLoseYn();
    }

    @Override
    public String component11() {
        return getRemark();
    }

    @Override
    public String component12() {
        return getTreatmentDetails();
    }

    @Override
    public LocalDate component13() {
        return getWithdrawalPeriodExpirationDate();
    }

    @Override
    public LocalDate value1() {
        return getDay();
    }

    @Override
    public String value2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value3() {
        return getEntityManagementNumber();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedTime();
    }

    @Override
    public LocalDate value5() {
        return getCureDate();
    }

    @Override
    public String value6() {
        return getDiseaseName();
    }

    @Override
    public String value7() {
        return getInjectionMethod();
    }

    @Override
    public String value8() {
        return getMedicationName();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedTime();
    }

    @Override
    public String value10() {
        return getNeedleLoseYn();
    }

    @Override
    public String value11() {
        return getRemark();
    }

    @Override
    public String value12() {
        return getTreatmentDetails();
    }

    @Override
    public LocalDate value13() {
        return getWithdrawalPeriodExpirationDate();
    }

    @Override
    public JDiseaseTreatmentRecord value1(LocalDate value) {
        setDay(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value2(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value3(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value4(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value5(LocalDate value) {
        setCureDate(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value6(String value) {
        setDiseaseName(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value7(String value) {
        setInjectionMethod(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value8(String value) {
        setMedicationName(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value9(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value10(String value) {
        setNeedleLoseYn(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value11(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value12(String value) {
        setTreatmentDetails(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value13(LocalDate value) {
        setWithdrawalPeriodExpirationDate(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord values(LocalDate value1, String value2, String value3, LocalDateTime value4, LocalDate value5, String value6, String value7, String value8, LocalDateTime value9, String value10, String value11, String value12, LocalDate value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDiseaseTreatmentRecord
     */
    public JDiseaseTreatmentRecord() {
        super(JDiseaseTreatment.DISEASE_TREATMENT);
    }

    /**
     * Create a detached, initialised JDiseaseTreatmentRecord
     */
    public JDiseaseTreatmentRecord(LocalDate day, String entityIdentificationNumber, String entityManagementNumber, LocalDateTime createdTime, LocalDate cureDate, String diseaseName, String injectionMethod, String medicationName, LocalDateTime modifiedTime, String needleLoseYn, String remark, String treatmentDetails, LocalDate withdrawalPeriodExpirationDate) {
        super(JDiseaseTreatment.DISEASE_TREATMENT);

        set(0, day);
        set(1, entityIdentificationNumber);
        set(2, entityManagementNumber);
        set(3, createdTime);
        set(4, cureDate);
        set(5, diseaseName);
        set(6, injectionMethod);
        set(7, medicationName);
        set(8, modifiedTime);
        set(9, needleLoseYn);
        set(10, remark);
        set(11, treatmentDetails);
        set(12, withdrawalPeriodExpirationDate);
    }
}
