/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JDiseaseTreatment;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record3;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDiseaseTreatmentRecord extends UpdatableRecordImpl<JDiseaseTreatmentRecord> implements Record11<String, String, Short, LocalDate, String, Short, String, String, String, String, LocalDate> {

    private static final long serialVersionUID = -351814952;

    /**
     * Setter for <code>naive-it-farm.disease_treatment.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.seq</code>.
     */
    public void setSeq(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.seq</code>.
     */
    public Short getSeq() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.cure_date</code>.
     */
    public void setCureDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.cure_date</code>.
     */
    public LocalDate getCureDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.disease_name</code>.
     */
    public void setDiseaseName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.disease_name</code>.
     */
    public String getDiseaseName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.fertilization_index</code>.
     */
    public void setFertilizationIndex(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.fertilization_index</code>.
     */
    public Short getFertilizationIndex() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.injection_method</code>.
     */
    public void setInjectionMethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.injection_method</code>.
     */
    public String getInjectionMethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.medication_name</code>.
     */
    public void setMedicationName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.medication_name</code>.
     */
    public String getMedicationName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.needle_lose_yn</code>.
     */
    public void setNeedleLoseYn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.needle_lose_yn</code>.
     */
    public String getNeedleLoseYn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.treatment_details</code>.
     */
    public void setTreatmentDetails(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.treatment_details</code>.
     */
    public String getTreatmentDetails() {
        return (String) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.disease_treatment.withdrawal_period_expiration_date</code>.
     */
    public void setWithdrawalPeriodExpirationDate(LocalDate value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.disease_treatment.withdrawal_period_expiration_date</code>.
     */
    public LocalDate getWithdrawalPeriodExpirationDate() {
        return (LocalDate) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, Short> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, String, Short, LocalDate, String, Short, String, String, String, String, LocalDate> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, String, Short, LocalDate, String, Short, String, String, String, String, LocalDate> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field2() {
        return JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<Short> field3() {
        return JDiseaseTreatment.DISEASE_TREATMENT.SEQ;
    }

    @Override
    public Field<LocalDate> field4() {
        return JDiseaseTreatment.DISEASE_TREATMENT.CURE_DATE;
    }

    @Override
    public Field<String> field5() {
        return JDiseaseTreatment.DISEASE_TREATMENT.DISEASE_NAME;
    }

    @Override
    public Field<Short> field6() {
        return JDiseaseTreatment.DISEASE_TREATMENT.FERTILIZATION_INDEX;
    }

    @Override
    public Field<String> field7() {
        return JDiseaseTreatment.DISEASE_TREATMENT.INJECTION_METHOD;
    }

    @Override
    public Field<String> field8() {
        return JDiseaseTreatment.DISEASE_TREATMENT.MEDICATION_NAME;
    }

    @Override
    public Field<String> field9() {
        return JDiseaseTreatment.DISEASE_TREATMENT.NEEDLE_LOSE_YN;
    }

    @Override
    public Field<String> field10() {
        return JDiseaseTreatment.DISEASE_TREATMENT.TREATMENT_DETAILS;
    }

    @Override
    public Field<LocalDate> field11() {
        return JDiseaseTreatment.DISEASE_TREATMENT.WITHDRAWAL_PERIOD_EXPIRATION_DATE;
    }

    @Override
    public String component1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component2() {
        return getEntityManagementNumber();
    }

    @Override
    public Short component3() {
        return getSeq();
    }

    @Override
    public LocalDate component4() {
        return getCureDate();
    }

    @Override
    public String component5() {
        return getDiseaseName();
    }

    @Override
    public Short component6() {
        return getFertilizationIndex();
    }

    @Override
    public String component7() {
        return getInjectionMethod();
    }

    @Override
    public String component8() {
        return getMedicationName();
    }

    @Override
    public String component9() {
        return getNeedleLoseYn();
    }

    @Override
    public String component10() {
        return getTreatmentDetails();
    }

    @Override
    public LocalDate component11() {
        return getWithdrawalPeriodExpirationDate();
    }

    @Override
    public String value1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value2() {
        return getEntityManagementNumber();
    }

    @Override
    public Short value3() {
        return getSeq();
    }

    @Override
    public LocalDate value4() {
        return getCureDate();
    }

    @Override
    public String value5() {
        return getDiseaseName();
    }

    @Override
    public Short value6() {
        return getFertilizationIndex();
    }

    @Override
    public String value7() {
        return getInjectionMethod();
    }

    @Override
    public String value8() {
        return getMedicationName();
    }

    @Override
    public String value9() {
        return getNeedleLoseYn();
    }

    @Override
    public String value10() {
        return getTreatmentDetails();
    }

    @Override
    public LocalDate value11() {
        return getWithdrawalPeriodExpirationDate();
    }

    @Override
    public JDiseaseTreatmentRecord value1(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value2(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value3(Short value) {
        setSeq(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value4(LocalDate value) {
        setCureDate(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value5(String value) {
        setDiseaseName(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value6(Short value) {
        setFertilizationIndex(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value7(String value) {
        setInjectionMethod(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value8(String value) {
        setMedicationName(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value9(String value) {
        setNeedleLoseYn(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value10(String value) {
        setTreatmentDetails(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord value11(LocalDate value) {
        setWithdrawalPeriodExpirationDate(value);
        return this;
    }

    @Override
    public JDiseaseTreatmentRecord values(String value1, String value2, Short value3, LocalDate value4, String value5, Short value6, String value7, String value8, String value9, String value10, LocalDate value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDiseaseTreatmentRecord
     */
    public JDiseaseTreatmentRecord() {
        super(JDiseaseTreatment.DISEASE_TREATMENT);
    }

    /**
     * Create a detached, initialised JDiseaseTreatmentRecord
     */
    public JDiseaseTreatmentRecord(String entityIdentificationNumber, String entityManagementNumber, Short seq, LocalDate cureDate, String diseaseName, Short fertilizationIndex, String injectionMethod, String medicationName, String needleLoseYn, String treatmentDetails, LocalDate withdrawalPeriodExpirationDate) {
        super(JDiseaseTreatment.DISEASE_TREATMENT);

        set(0, entityIdentificationNumber);
        set(1, entityManagementNumber);
        set(2, seq);
        set(3, cureDate);
        set(4, diseaseName);
        set(5, fertilizationIndex);
        set(6, injectionMethod);
        set(7, medicationName);
        set(8, needleLoseYn);
        set(9, treatmentDetails);
        set(10, withdrawalPeriodExpirationDate);
    }
}
