/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JHouseKeepingBook;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JHouseKeepingBookRecord extends UpdatableRecordImpl<JHouseKeepingBookRecord> implements Record6<String, String, LocalDateTime, Long, String, String> {

    private static final long serialVersionUID = 1102777236;

    /**
     * Setter for <code>naive-it-farm.house_keeping_book.management_no</code>. 관리번호
     */
    public void setManagementNo(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.house_keeping_book.management_no</code>. 관리번호
     */
    public String getManagementNo() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.house_keeping_book.category_code</code>. 수입/지출 카테고리
     */
    public void setCategoryCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.house_keeping_book.category_code</code>. 수입/지출 카테고리
     */
    public String getCategoryCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.house_keeping_book.business_day</code>.
     */
    public void setBusinessDay(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.house_keeping_book.business_day</code>.
     */
    public LocalDateTime getBusinessDay() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.house_keeping_book.amount</code>.
     */
    public void setAmount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.house_keeping_book.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.house_keeping_book.breakdown</code>.
     */
    public void setBreakdown(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.house_keeping_book.breakdown</code>.
     */
    public String getBreakdown() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.house_keeping_book.detail_contents</code>. 메모
     */
    public void setDetailContents(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.house_keeping_book.detail_contents</code>. 메모
     */
    public String getDetailContents() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, LocalDateTime, Long, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, LocalDateTime, Long, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JHouseKeepingBook.HOUSE_KEEPING_BOOK.MANAGEMENT_NO;
    }

    @Override
    public Field<String> field2() {
        return JHouseKeepingBook.HOUSE_KEEPING_BOOK.CATEGORY_CODE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return JHouseKeepingBook.HOUSE_KEEPING_BOOK.BUSINESS_DAY;
    }

    @Override
    public Field<Long> field4() {
        return JHouseKeepingBook.HOUSE_KEEPING_BOOK.AMOUNT;
    }

    @Override
    public Field<String> field5() {
        return JHouseKeepingBook.HOUSE_KEEPING_BOOK.BREAKDOWN;
    }

    @Override
    public Field<String> field6() {
        return JHouseKeepingBook.HOUSE_KEEPING_BOOK.DETAIL_CONTENTS;
    }

    @Override
    public String component1() {
        return getManagementNo();
    }

    @Override
    public String component2() {
        return getCategoryCode();
    }

    @Override
    public LocalDateTime component3() {
        return getBusinessDay();
    }

    @Override
    public Long component4() {
        return getAmount();
    }

    @Override
    public String component5() {
        return getBreakdown();
    }

    @Override
    public String component6() {
        return getDetailContents();
    }

    @Override
    public String value1() {
        return getManagementNo();
    }

    @Override
    public String value2() {
        return getCategoryCode();
    }

    @Override
    public LocalDateTime value3() {
        return getBusinessDay();
    }

    @Override
    public Long value4() {
        return getAmount();
    }

    @Override
    public String value5() {
        return getBreakdown();
    }

    @Override
    public String value6() {
        return getDetailContents();
    }

    @Override
    public JHouseKeepingBookRecord value1(String value) {
        setManagementNo(value);
        return this;
    }

    @Override
    public JHouseKeepingBookRecord value2(String value) {
        setCategoryCode(value);
        return this;
    }

    @Override
    public JHouseKeepingBookRecord value3(LocalDateTime value) {
        setBusinessDay(value);
        return this;
    }

    @Override
    public JHouseKeepingBookRecord value4(Long value) {
        setAmount(value);
        return this;
    }

    @Override
    public JHouseKeepingBookRecord value5(String value) {
        setBreakdown(value);
        return this;
    }

    @Override
    public JHouseKeepingBookRecord value6(String value) {
        setDetailContents(value);
        return this;
    }

    @Override
    public JHouseKeepingBookRecord values(String value1, String value2, LocalDateTime value3, Long value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JHouseKeepingBookRecord
     */
    public JHouseKeepingBookRecord() {
        super(JHouseKeepingBook.HOUSE_KEEPING_BOOK);
    }

    /**
     * Create a detached, initialised JHouseKeepingBookRecord
     */
    public JHouseKeepingBookRecord(String managementNo, String categoryCode, LocalDateTime businessDay, Long amount, String breakdown, String detailContents) {
        super(JHouseKeepingBook.HOUSE_KEEPING_BOOK);

        set(0, managementNo);
        set(1, categoryCode);
        set(2, businessDay);
        set(3, amount);
        set(4, breakdown);
        set(5, detailContents);
    }
}
