/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JLocalBeefManagement;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Record2;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLocalBeefManagementRecord extends UpdatableRecordImpl<JLocalBeefManagementRecord> implements Record14<String, String, LocalDate, LocalDate, LocalDateTime, LocalDate, LocalDate, String, LocalDateTime, String, String, String, Boolean, String> {

    private static final long serialVersionUID = -253193981;

    /**
     * Setter for <code>naive-it-farm.local_beef_management.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.birth_day</code>.
     */
    public void setBirthDay(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.birth_day</code>.
     */
    public LocalDate getBirthDay() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.castration_date</code>.
     */
    public void setCastrationDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.castration_date</code>.
     */
    public LocalDate getCastrationDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.ear_tag_date</code>.
     */
    public void setEarTagDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.ear_tag_date</code>.
     */
    public LocalDate getEarTagDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.enter_date</code>.
     */
    public void setEnterDate(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.enter_date</code>.
     */
    public LocalDate getEnterDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.gender</code>.
     */
    public void setGender(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.gender</code>.
     */
    public String getGender() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.parent_mom_no</code>.
     */
    public void setParentMomNo(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.parent_mom_no</code>.
     */
    public String getParentMomNo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.parent_papa_no</code>.
     */
    public void setParentPapaNo(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.parent_papa_no</code>.
     */
    public String getParentPapaNo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.sell_yn</code>.
     */
    public void setSellYn(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.sell_yn</code>.
     */
    public String getSellYn() {
        return (String) get(11);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.delete_yn</code>.
     */
    public void setDeleteYn(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.delete_yn</code>.
     */
    public Boolean getDeleteYn() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>naive-it-farm.local_beef_management.room_number</code>.
     */
    public void setRoomNumber(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>naive-it-farm.local_beef_management.room_number</code>.
     */
    public String getRoomNumber() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, LocalDate, LocalDate, LocalDateTime, LocalDate, LocalDate, String, LocalDateTime, String, String, String, Boolean, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<String, String, LocalDate, LocalDate, LocalDateTime, LocalDate, LocalDate, String, LocalDateTime, String, String, String, Boolean, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field2() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<LocalDate> field3() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.BIRTH_DAY;
    }

    @Override
    public Field<LocalDate> field4() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.CASTRATION_DATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.CREATED_TIME;
    }

    @Override
    public Field<LocalDate> field6() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.EAR_TAG_DATE;
    }

    @Override
    public Field<LocalDate> field7() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.ENTER_DATE;
    }

    @Override
    public Field<String> field8() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.GENDER;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.MODIFIED_TIME;
    }

    @Override
    public Field<String> field10() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.PARENT_MOM_NO;
    }

    @Override
    public Field<String> field11() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.PARENT_PAPA_NO;
    }

    @Override
    public Field<String> field12() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.SELL_YN;
    }

    @Override
    public Field<Boolean> field13() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.DELETE_YN;
    }

    @Override
    public Field<String> field14() {
        return JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.ROOM_NUMBER;
    }

    @Override
    public String component1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component2() {
        return getEntityManagementNumber();
    }

    @Override
    public LocalDate component3() {
        return getBirthDay();
    }

    @Override
    public LocalDate component4() {
        return getCastrationDate();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedTime();
    }

    @Override
    public LocalDate component6() {
        return getEarTagDate();
    }

    @Override
    public LocalDate component7() {
        return getEnterDate();
    }

    @Override
    public String component8() {
        return getGender();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedTime();
    }

    @Override
    public String component10() {
        return getParentMomNo();
    }

    @Override
    public String component11() {
        return getParentPapaNo();
    }

    @Override
    public String component12() {
        return getSellYn();
    }

    @Override
    public Boolean component13() {
        return getDeleteYn();
    }

    @Override
    public String component14() {
        return getRoomNumber();
    }

    @Override
    public String value1() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value2() {
        return getEntityManagementNumber();
    }

    @Override
    public LocalDate value3() {
        return getBirthDay();
    }

    @Override
    public LocalDate value4() {
        return getCastrationDate();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedTime();
    }

    @Override
    public LocalDate value6() {
        return getEarTagDate();
    }

    @Override
    public LocalDate value7() {
        return getEnterDate();
    }

    @Override
    public String value8() {
        return getGender();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedTime();
    }

    @Override
    public String value10() {
        return getParentMomNo();
    }

    @Override
    public String value11() {
        return getParentPapaNo();
    }

    @Override
    public String value12() {
        return getSellYn();
    }

    @Override
    public Boolean value13() {
        return getDeleteYn();
    }

    @Override
    public String value14() {
        return getRoomNumber();
    }

    @Override
    public JLocalBeefManagementRecord value1(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value2(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value3(LocalDate value) {
        setBirthDay(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value4(LocalDate value) {
        setCastrationDate(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value5(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value6(LocalDate value) {
        setEarTagDate(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value7(LocalDate value) {
        setEnterDate(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value8(String value) {
        setGender(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value9(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value10(String value) {
        setParentMomNo(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value11(String value) {
        setParentPapaNo(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value12(String value) {
        setSellYn(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value13(Boolean value) {
        setDeleteYn(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord value14(String value) {
        setRoomNumber(value);
        return this;
    }

    @Override
    public JLocalBeefManagementRecord values(String value1, String value2, LocalDate value3, LocalDate value4, LocalDateTime value5, LocalDate value6, LocalDate value7, String value8, LocalDateTime value9, String value10, String value11, String value12, Boolean value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JLocalBeefManagementRecord
     */
    public JLocalBeefManagementRecord() {
        super(JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT);
    }

    /**
     * Create a detached, initialised JLocalBeefManagementRecord
     */
    public JLocalBeefManagementRecord(String entityIdentificationNumber, String entityManagementNumber, LocalDate birthDay, LocalDate castrationDate, LocalDateTime createdTime, LocalDate earTagDate, LocalDate enterDate, String gender, LocalDateTime modifiedTime, String parentMomNo, String parentPapaNo, String sellYn, Boolean deleteYn, String roomNumber) {
        super(JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT);

        set(0, entityIdentificationNumber);
        set(1, entityManagementNumber);
        set(2, birthDay);
        set(3, castrationDate);
        set(4, createdTime);
        set(5, earTagDate);
        set(6, enterDate);
        set(7, gender);
        set(8, modifiedTime);
        set(9, parentMomNo);
        set(10, parentPapaNo);
        set(11, sellYn);
        set(12, deleteYn);
        set(13, roomNumber);
    }
}
