/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JPersonalCode;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPersonalCodeRecord extends UpdatableRecordImpl<JPersonalCodeRecord> implements Record7<String, String, String, Integer, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1720625271;

    /**
     * Setter for <code>naive-it-farm.personal_code.code</code>.
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.personal_code.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.personal_code.upper_code</code>. 부모코드
     */
    public void setUpperCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.personal_code.upper_code</code>. 부모코드
     */
    public String getUpperCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.personal_code.user_id</code>. 사용자 아이디
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.personal_code.user_id</code>. 사용자 아이디
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.personal_code.code_seq</code>. 순서
     */
    public void setCodeSeq(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.personal_code.code_seq</code>. 순서
     */
    public Integer getCodeSeq() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.personal_code.code_name</code>. 코드명
     */
    public void setCodeName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.personal_code.code_name</code>. 코드명
     */
    public String getCodeName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.personal_code.code_comments</code>. 코드 상세
     */
    public void setCodeComments(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.personal_code.code_comments</code>. 코드 상세
     */
    public String getCodeComments() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.personal_code.created_time</code>. 생성일시
     */
    public void setCreatedTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.personal_code.created_time</code>. 생성일시
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, Integer, String, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JPersonalCode.PERSONAL_CODE.CODE;
    }

    @Override
    public Field<String> field2() {
        return JPersonalCode.PERSONAL_CODE.UPPER_CODE;
    }

    @Override
    public Field<String> field3() {
        return JPersonalCode.PERSONAL_CODE.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return JPersonalCode.PERSONAL_CODE.CODE_SEQ;
    }

    @Override
    public Field<String> field5() {
        return JPersonalCode.PERSONAL_CODE.CODE_NAME;
    }

    @Override
    public Field<String> field6() {
        return JPersonalCode.PERSONAL_CODE.CODE_COMMENTS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JPersonalCode.PERSONAL_CODE.CREATED_TIME;
    }

    @Override
    public String component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getUpperCode();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getCodeSeq();
    }

    @Override
    public String component5() {
        return getCodeName();
    }

    @Override
    public String component6() {
        return getCodeComments();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedTime();
    }

    @Override
    public String value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getUpperCode();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getCodeSeq();
    }

    @Override
    public String value5() {
        return getCodeName();
    }

    @Override
    public String value6() {
        return getCodeComments();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedTime();
    }

    @Override
    public JPersonalCodeRecord value1(String value) {
        setCode(value);
        return this;
    }

    @Override
    public JPersonalCodeRecord value2(String value) {
        setUpperCode(value);
        return this;
    }

    @Override
    public JPersonalCodeRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public JPersonalCodeRecord value4(Integer value) {
        setCodeSeq(value);
        return this;
    }

    @Override
    public JPersonalCodeRecord value5(String value) {
        setCodeName(value);
        return this;
    }

    @Override
    public JPersonalCodeRecord value6(String value) {
        setCodeComments(value);
        return this;
    }

    @Override
    public JPersonalCodeRecord value7(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JPersonalCodeRecord values(String value1, String value2, String value3, Integer value4, String value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JPersonalCodeRecord
     */
    public JPersonalCodeRecord() {
        super(JPersonalCode.PERSONAL_CODE);
    }

    /**
     * Create a detached, initialised JPersonalCodeRecord
     */
    public JPersonalCodeRecord(String code, String upperCode, String userId, Integer codeSeq, String codeName, String codeComments, LocalDateTime createdTime) {
        super(JPersonalCode.PERSONAL_CODE);

        set(0, code);
        set(1, upperCode);
        set(2, userId);
        set(3, codeSeq);
        set(4, codeName);
        set(5, codeComments);
        set(6, createdTime);
    }
}
