/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JSchedule;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JScheduleRecord extends UpdatableRecordImpl<JScheduleRecord> implements Record11<String, String, LocalDateTime, Short, Short, LocalDateTime, String, Short, LocalDate, String, String> {

    private static final long serialVersionUID = 352516693;

    /**
     * Setter for <code>naive-it-farm.schedule.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.maximum_temperature</code>.
     */
    public void setMaximumTemperature(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.maximum_temperature</code>.
     */
    public Short getMaximumTemperature() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.minimum_temperature</code>.
     */
    public void setMinimumTemperature(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.minimum_temperature</code>.
     */
    public Short getMinimumTemperature() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.public_yn</code>.
     */
    public void setPublicYn(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.public_yn</code>.
     */
    public String getPublicYn() {
        return (String) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.seq</code>.
     */
    public void setSeq(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.seq</code>.
     */
    public Short getSeq() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.standard_date</code>.
     */
    public void setStandardDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.standard_date</code>.
     */
    public LocalDate getStandardDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.subject</code>.
     */
    public void setSubject(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.subject</code>.
     */
    public String getSubject() {
        return (String) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.today_weather_code</code>.
     */
    public void setTodayWeatherCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.today_weather_code</code>.
     */
    public String getTodayWeatherCode() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, String, LocalDateTime, Short, Short, LocalDateTime, String, Short, LocalDate, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, String, LocalDateTime, Short, Short, LocalDateTime, String, Short, LocalDate, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JSchedule.SCHEDULE.UUID;
    }

    @Override
    public Field<String> field2() {
        return JSchedule.SCHEDULE.CONTENT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return JSchedule.SCHEDULE.CREATE_TIME;
    }

    @Override
    public Field<Short> field4() {
        return JSchedule.SCHEDULE.MAXIMUM_TEMPERATURE;
    }

    @Override
    public Field<Short> field5() {
        return JSchedule.SCHEDULE.MINIMUM_TEMPERATURE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return JSchedule.SCHEDULE.MODIFIED_TIME;
    }

    @Override
    public Field<String> field7() {
        return JSchedule.SCHEDULE.PUBLIC_YN;
    }

    @Override
    public Field<Short> field8() {
        return JSchedule.SCHEDULE.SEQ;
    }

    @Override
    public Field<LocalDate> field9() {
        return JSchedule.SCHEDULE.STANDARD_DATE;
    }

    @Override
    public Field<String> field10() {
        return JSchedule.SCHEDULE.SUBJECT;
    }

    @Override
    public Field<String> field11() {
        return JSchedule.SCHEDULE.TODAY_WEATHER_CODE;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public Short component4() {
        return getMaximumTemperature();
    }

    @Override
    public Short component5() {
        return getMinimumTemperature();
    }

    @Override
    public LocalDateTime component6() {
        return getModifiedTime();
    }

    @Override
    public String component7() {
        return getPublicYn();
    }

    @Override
    public Short component8() {
        return getSeq();
    }

    @Override
    public LocalDate component9() {
        return getStandardDate();
    }

    @Override
    public String component10() {
        return getSubject();
    }

    @Override
    public String component11() {
        return getTodayWeatherCode();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public Short value4() {
        return getMaximumTemperature();
    }

    @Override
    public Short value5() {
        return getMinimumTemperature();
    }

    @Override
    public LocalDateTime value6() {
        return getModifiedTime();
    }

    @Override
    public String value7() {
        return getPublicYn();
    }

    @Override
    public Short value8() {
        return getSeq();
    }

    @Override
    public LocalDate value9() {
        return getStandardDate();
    }

    @Override
    public String value10() {
        return getSubject();
    }

    @Override
    public String value11() {
        return getTodayWeatherCode();
    }

    @Override
    public JScheduleRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public JScheduleRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public JScheduleRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public JScheduleRecord value4(Short value) {
        setMaximumTemperature(value);
        return this;
    }

    @Override
    public JScheduleRecord value5(Short value) {
        setMinimumTemperature(value);
        return this;
    }

    @Override
    public JScheduleRecord value6(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public JScheduleRecord value7(String value) {
        setPublicYn(value);
        return this;
    }

    @Override
    public JScheduleRecord value8(Short value) {
        setSeq(value);
        return this;
    }

    @Override
    public JScheduleRecord value9(LocalDate value) {
        setStandardDate(value);
        return this;
    }

    @Override
    public JScheduleRecord value10(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public JScheduleRecord value11(String value) {
        setTodayWeatherCode(value);
        return this;
    }

    @Override
    public JScheduleRecord values(String value1, String value2, LocalDateTime value3, Short value4, Short value5, LocalDateTime value6, String value7, Short value8, LocalDate value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JScheduleRecord
     */
    public JScheduleRecord() {
        super(JSchedule.SCHEDULE);
    }

    /**
     * Create a detached, initialised JScheduleRecord
     */
    public JScheduleRecord(String uuid, String content, LocalDateTime createTime, Short maximumTemperature, Short minimumTemperature, LocalDateTime modifiedTime, String publicYn, Short seq, LocalDate standardDate, String subject, String todayWeatherCode) {
        super(JSchedule.SCHEDULE);

        set(0, uuid);
        set(1, content);
        set(2, createTime);
        set(3, maximumTemperature);
        set(4, minimumTemperature);
        set(5, modifiedTime);
        set(6, publicYn);
        set(7, seq);
        set(8, standardDate);
        set(9, subject);
        set(10, todayWeatherCode);
    }
}
