/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JSchedule;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Record2;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JScheduleRecord extends UpdatableRecordImpl<JScheduleRecord> implements Record15<Long, Long, String, String, String, String, String, String, Long, Long, LocalDateTime, LocalDateTime, String, Integer, String> {

    private static final long serialVersionUID = 1008138080;

    /**
     * Setter for <code>naive-it-farm.schedule.sch_mgt_no</code>. 일정관리번호
     */
    public void setSchMgtNo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.sch_mgt_no</code>. 일정관리번호
     */
    public Long getSchMgtNo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.sch_seq</code>. 같은날의 순번
     */
    public void setSchSeq(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.sch_seq</code>. 같은날의 순번
     */
    public Long getSchSeq() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.sch_subject</code>. 제목
     */
    public void setSchSubject(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.sch_subject</code>. 제목
     */
    public String getSchSubject() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.sch_content</code>.
     */
    public void setSchContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.sch_content</code>.
     */
    public String getSchContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.std_date</code>. 기준날짜

     */
    public void setStdDate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.std_date</code>. 기준날짜

     */
    public String getStdDate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.today_weather_code</code>. 오늘 날씨 ('맑음......')
     */
    public void setTodayWeatherCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.today_weather_code</code>. 오늘 날씨 ('맑음......')
     */
    public String getTodayWeatherCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.min_degreespoint_code</code>.
     */
    public void setMinDegreespointCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.min_degreespoint_code</code>.
     */
    public String getMinDegreespointCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.max_degreespoint_code</code>.
     */
    public void setMaxDegreespointCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.max_degreespoint_code</code>.
     */
    public String getMaxDegreespointCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.min_temperature</code>. 최저 기온

     */
    public void setMinTemperature(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.min_temperature</code>. 최저 기온

     */
    public Long getMinTemperature() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.max_temperature</code>. 최고온도
     */
    public void setMaxTemperature(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.max_temperature</code>. 최고온도
     */
    public Long getMaxTemperature() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.create_time</code>. 생성시간
     */
    public void setCreateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.create_time</code>. 생성시간
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.modify_time</code>. 수정시간
     */
    public void setModifyTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.modify_time</code>. 수정시간
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.public_yn</code>. 공개 여부 'Y' : 공개  'N' 비공개
     */
    public void setPublicYn(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.public_yn</code>. 공개 여부 'Y' : 공개  'N' 비공개
     */
    public String getPublicYn() {
        return (String) get(12);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.group_no</code>. 그룹번호
     */
    public void setGroupNo(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.group_no</code>. 그룹번호
     */
    public Integer getGroupNo() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>naive-it-farm.schedule.user_id</code>. 사용자 아이디
     */
    public void setUserId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>naive-it-farm.schedule.user_id</code>. 사용자 아이디
     */
    public String getUserId() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, Long, String, String, String, String, String, String, Long, Long, LocalDateTime, LocalDateTime, String, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, Long, String, String, String, String, String, String, Long, Long, LocalDateTime, LocalDateTime, String, Integer, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return JSchedule.SCHEDULE.SCH_MGT_NO;
    }

    @Override
    public Field<Long> field2() {
        return JSchedule.SCHEDULE.SCH_SEQ;
    }

    @Override
    public Field<String> field3() {
        return JSchedule.SCHEDULE.SCH_SUBJECT;
    }

    @Override
    public Field<String> field4() {
        return JSchedule.SCHEDULE.SCH_CONTENT;
    }

    @Override
    public Field<String> field5() {
        return JSchedule.SCHEDULE.STD_DATE;
    }

    @Override
    public Field<String> field6() {
        return JSchedule.SCHEDULE.TODAY_WEATHER_CODE;
    }

    @Override
    public Field<String> field7() {
        return JSchedule.SCHEDULE.MIN_DEGREESPOINT_CODE;
    }

    @Override
    public Field<String> field8() {
        return JSchedule.SCHEDULE.MAX_DEGREESPOINT_CODE;
    }

    @Override
    public Field<Long> field9() {
        return JSchedule.SCHEDULE.MIN_TEMPERATURE;
    }

    @Override
    public Field<Long> field10() {
        return JSchedule.SCHEDULE.MAX_TEMPERATURE;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return JSchedule.SCHEDULE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return JSchedule.SCHEDULE.MODIFY_TIME;
    }

    @Override
    public Field<String> field13() {
        return JSchedule.SCHEDULE.PUBLIC_YN;
    }

    @Override
    public Field<Integer> field14() {
        return JSchedule.SCHEDULE.GROUP_NO;
    }

    @Override
    public Field<String> field15() {
        return JSchedule.SCHEDULE.USER_ID;
    }

    @Override
    public Long component1() {
        return getSchMgtNo();
    }

    @Override
    public Long component2() {
        return getSchSeq();
    }

    @Override
    public String component3() {
        return getSchSubject();
    }

    @Override
    public String component4() {
        return getSchContent();
    }

    @Override
    public String component5() {
        return getStdDate();
    }

    @Override
    public String component6() {
        return getTodayWeatherCode();
    }

    @Override
    public String component7() {
        return getMinDegreespointCode();
    }

    @Override
    public String component8() {
        return getMaxDegreespointCode();
    }

    @Override
    public Long component9() {
        return getMinTemperature();
    }

    @Override
    public Long component10() {
        return getMaxTemperature();
    }

    @Override
    public LocalDateTime component11() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component12() {
        return getModifyTime();
    }

    @Override
    public String component13() {
        return getPublicYn();
    }

    @Override
    public Integer component14() {
        return getGroupNo();
    }

    @Override
    public String component15() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getSchMgtNo();
    }

    @Override
    public Long value2() {
        return getSchSeq();
    }

    @Override
    public String value3() {
        return getSchSubject();
    }

    @Override
    public String value4() {
        return getSchContent();
    }

    @Override
    public String value5() {
        return getStdDate();
    }

    @Override
    public String value6() {
        return getTodayWeatherCode();
    }

    @Override
    public String value7() {
        return getMinDegreespointCode();
    }

    @Override
    public String value8() {
        return getMaxDegreespointCode();
    }

    @Override
    public Long value9() {
        return getMinTemperature();
    }

    @Override
    public Long value10() {
        return getMaxTemperature();
    }

    @Override
    public LocalDateTime value11() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value12() {
        return getModifyTime();
    }

    @Override
    public String value13() {
        return getPublicYn();
    }

    @Override
    public Integer value14() {
        return getGroupNo();
    }

    @Override
    public String value15() {
        return getUserId();
    }

    @Override
    public JScheduleRecord value1(Long value) {
        setSchMgtNo(value);
        return this;
    }

    @Override
    public JScheduleRecord value2(Long value) {
        setSchSeq(value);
        return this;
    }

    @Override
    public JScheduleRecord value3(String value) {
        setSchSubject(value);
        return this;
    }

    @Override
    public JScheduleRecord value4(String value) {
        setSchContent(value);
        return this;
    }

    @Override
    public JScheduleRecord value5(String value) {
        setStdDate(value);
        return this;
    }

    @Override
    public JScheduleRecord value6(String value) {
        setTodayWeatherCode(value);
        return this;
    }

    @Override
    public JScheduleRecord value7(String value) {
        setMinDegreespointCode(value);
        return this;
    }

    @Override
    public JScheduleRecord value8(String value) {
        setMaxDegreespointCode(value);
        return this;
    }

    @Override
    public JScheduleRecord value9(Long value) {
        setMinTemperature(value);
        return this;
    }

    @Override
    public JScheduleRecord value10(Long value) {
        setMaxTemperature(value);
        return this;
    }

    @Override
    public JScheduleRecord value11(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public JScheduleRecord value12(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public JScheduleRecord value13(String value) {
        setPublicYn(value);
        return this;
    }

    @Override
    public JScheduleRecord value14(Integer value) {
        setGroupNo(value);
        return this;
    }

    @Override
    public JScheduleRecord value15(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public JScheduleRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, Long value9, Long value10, LocalDateTime value11, LocalDateTime value12, String value13, Integer value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JScheduleRecord
     */
    public JScheduleRecord() {
        super(JSchedule.SCHEDULE);
    }

    /**
     * Create a detached, initialised JScheduleRecord
     */
    public JScheduleRecord(Long schMgtNo, Long schSeq, String schSubject, String schContent, String stdDate, String todayWeatherCode, String minDegreespointCode, String maxDegreespointCode, Long minTemperature, Long maxTemperature, LocalDateTime createTime, LocalDateTime modifyTime, String publicYn, Integer groupNo, String userId) {
        super(JSchedule.SCHEDULE);

        set(0, schMgtNo);
        set(1, schSeq);
        set(2, schSubject);
        set(3, schContent);
        set(4, stdDate);
        set(5, todayWeatherCode);
        set(6, minDegreespointCode);
        set(7, maxDegreespointCode);
        set(8, minTemperature);
        set(9, maxTemperature);
        set(10, createTime);
        set(11, modifyTime);
        set(12, publicYn);
        set(13, groupNo);
        set(14, userId);
    }
}
