/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JUsers;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JUsersRecord extends UpdatableRecordImpl<JUsersRecord> implements Record14<String, String, String, Long, LocalDateTime, String, LocalDateTime, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1077694889;

    /**
     * Setter for <code>naive-it-farm.users.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.users.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.users.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.users.fail_login_count</code>.
     */
    public void setFailLoginCount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.fail_login_count</code>.
     */
    public Long getFailLoginCount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.users.fail_login_time</code>.
     */
    public void setFailLoginTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.fail_login_time</code>.
     */
    public LocalDateTime getFailLoginTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.users.gender</code>.
     */
    public void setGender(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.gender</code>.
     */
    public String getGender() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.users.last_login_time</code>.
     */
    public void setLastLoginTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.last_login_time</code>.
     */
    public LocalDateTime getLastLoginTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.users.mobile_phone_number</code>.
     */
    public void setMobilePhoneNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.mobile_phone_number</code>.
     */
    public String getMobilePhoneNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.users.password</code>.
     */
    public void setPassword(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.password</code>.
     */
    public String getPassword() {
        return (String) get(8);
    }

    /**
     * Setter for <code>naive-it-farm.users.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>naive-it-farm.users.ssn_number</code>.
     */
    public void setSsnNumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.ssn_number</code>.
     */
    public String getSsnNumber() {
        return (String) get(10);
    }

    /**
     * Setter for <code>naive-it-farm.users.use_lock_state</code>.
     */
    public void setUseLockState(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.use_lock_state</code>.
     */
    public String getUseLockState() {
        return (String) get(11);
    }

    /**
     * Setter for <code>naive-it-farm.users.user_id</code>.
     */
    public void setUserId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.user_id</code>.
     */
    public String getUserId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>naive-it-farm.users.user_name</code>.
     */
    public void setUserName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>naive-it-farm.users.user_name</code>.
     */
    public String getUserName() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, Long, LocalDateTime, String, LocalDateTime, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<String, String, String, Long, LocalDateTime, String, LocalDateTime, String, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JUsers.USERS.UUID;
    }

    @Override
    public Field<String> field2() {
        return JUsers.USERS.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return JUsers.USERS.EMAIL;
    }

    @Override
    public Field<Long> field4() {
        return JUsers.USERS.FAIL_LOGIN_COUNT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JUsers.USERS.FAIL_LOGIN_TIME;
    }

    @Override
    public Field<String> field6() {
        return JUsers.USERS.GENDER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JUsers.USERS.LAST_LOGIN_TIME;
    }

    @Override
    public Field<String> field8() {
        return JUsers.USERS.MOBILE_PHONE_NUMBER;
    }

    @Override
    public Field<String> field9() {
        return JUsers.USERS.PASSWORD;
    }

    @Override
    public Field<String> field10() {
        return JUsers.USERS.PHONE_NUMBER;
    }

    @Override
    public Field<String> field11() {
        return JUsers.USERS.SSN_NUMBER;
    }

    @Override
    public Field<String> field12() {
        return JUsers.USERS.USE_LOCK_STATE;
    }

    @Override
    public Field<String> field13() {
        return JUsers.USERS.USER_ID;
    }

    @Override
    public Field<String> field14() {
        return JUsers.USERS.USER_NAME;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public Long component4() {
        return getFailLoginCount();
    }

    @Override
    public LocalDateTime component5() {
        return getFailLoginTime();
    }

    @Override
    public String component6() {
        return getGender();
    }

    @Override
    public LocalDateTime component7() {
        return getLastLoginTime();
    }

    @Override
    public String component8() {
        return getMobilePhoneNumber();
    }

    @Override
    public String component9() {
        return getPassword();
    }

    @Override
    public String component10() {
        return getPhoneNumber();
    }

    @Override
    public String component11() {
        return getSsnNumber();
    }

    @Override
    public String component12() {
        return getUseLockState();
    }

    @Override
    public String component13() {
        return getUserId();
    }

    @Override
    public String component14() {
        return getUserName();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public Long value4() {
        return getFailLoginCount();
    }

    @Override
    public LocalDateTime value5() {
        return getFailLoginTime();
    }

    @Override
    public String value6() {
        return getGender();
    }

    @Override
    public LocalDateTime value7() {
        return getLastLoginTime();
    }

    @Override
    public String value8() {
        return getMobilePhoneNumber();
    }

    @Override
    public String value9() {
        return getPassword();
    }

    @Override
    public String value10() {
        return getPhoneNumber();
    }

    @Override
    public String value11() {
        return getSsnNumber();
    }

    @Override
    public String value12() {
        return getUseLockState();
    }

    @Override
    public String value13() {
        return getUserId();
    }

    @Override
    public String value14() {
        return getUserName();
    }

    @Override
    public JUsersRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public JUsersRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public JUsersRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public JUsersRecord value4(Long value) {
        setFailLoginCount(value);
        return this;
    }

    @Override
    public JUsersRecord value5(LocalDateTime value) {
        setFailLoginTime(value);
        return this;
    }

    @Override
    public JUsersRecord value6(String value) {
        setGender(value);
        return this;
    }

    @Override
    public JUsersRecord value7(LocalDateTime value) {
        setLastLoginTime(value);
        return this;
    }

    @Override
    public JUsersRecord value8(String value) {
        setMobilePhoneNumber(value);
        return this;
    }

    @Override
    public JUsersRecord value9(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public JUsersRecord value10(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public JUsersRecord value11(String value) {
        setSsnNumber(value);
        return this;
    }

    @Override
    public JUsersRecord value12(String value) {
        setUseLockState(value);
        return this;
    }

    @Override
    public JUsersRecord value13(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public JUsersRecord value14(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public JUsersRecord values(String value1, String value2, String value3, Long value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JUsersRecord
     */
    public JUsersRecord() {
        super(JUsers.USERS);
    }

    /**
     * Create a detached, initialised JUsersRecord
     */
    public JUsersRecord(String uuid, String description, String email, Long failLoginCount, LocalDateTime failLoginTime, String gender, LocalDateTime lastLoginTime, String mobilePhoneNumber, String password, String phoneNumber, String ssnNumber, String useLockState, String userId, String userName) {
        super(JUsers.USERS);

        set(0, uuid);
        set(1, description);
        set(2, email);
        set(3, failLoginCount);
        set(4, failLoginTime);
        set(5, gender);
        set(6, lastLoginTime);
        set(7, mobilePhoneNumber);
        set(8, password);
        set(9, phoneNumber);
        set(10, ssnNumber);
        set(11, useLockState);
        set(12, userId);
        set(13, userName);
    }
}
