/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain.tables.records;


import com.skan.farm.domain.tables.JVaccination;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JVaccinationRecord extends UpdatableRecordImpl<JVaccinationRecord> implements Record9<LocalDate, String, String, Short, LocalDateTime, String, LocalDateTime, String, String> {

    private static final long serialVersionUID = -681779344;

    /**
     * Setter for <code>naive-it-farm.vaccination.day</code>.
     */
    public void setDay(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.day</code>.
     */
    public LocalDate getDay() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.entity_identification_number</code>.
     */
    public void setEntityIdentificationNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.entity_identification_number</code>.
     */
    public String getEntityIdentificationNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.entity_management_number</code>.
     */
    public void setEntityManagementNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.entity_management_number</code>.
     */
    public String getEntityManagementNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.seq</code>.
     */
    public void setSeq(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.seq</code>.
     */
    public Short getSeq() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.location</code>.
     */
    public void setLocation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.location</code>.
     */
    public String getLocation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.remark</code>.
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.remark</code>.
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>naive-it-farm.vaccination.vaccination_type</code>.
     */
    public void setVaccinationType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>naive-it-farm.vaccination.vaccination_type</code>.
     */
    public String getVaccinationType() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<LocalDate, String, String, Short> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<LocalDate, String, String, Short, LocalDateTime, String, LocalDateTime, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<LocalDate, String, String, Short, LocalDateTime, String, LocalDateTime, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<LocalDate> field1() {
        return JVaccination.VACCINATION.DAY;
    }

    @Override
    public Field<String> field2() {
        return JVaccination.VACCINATION.ENTITY_IDENTIFICATION_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return JVaccination.VACCINATION.ENTITY_MANAGEMENT_NUMBER;
    }

    @Override
    public Field<Short> field4() {
        return JVaccination.VACCINATION.SEQ;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JVaccination.VACCINATION.CREATED_TIME;
    }

    @Override
    public Field<String> field6() {
        return JVaccination.VACCINATION.LOCATION;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JVaccination.VACCINATION.MODIFIED_TIME;
    }

    @Override
    public Field<String> field8() {
        return JVaccination.VACCINATION.REMARK;
    }

    @Override
    public Field<String> field9() {
        return JVaccination.VACCINATION.VACCINATION_TYPE;
    }

    @Override
    public LocalDate component1() {
        return getDay();
    }

    @Override
    public String component2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String component3() {
        return getEntityManagementNumber();
    }

    @Override
    public Short component4() {
        return getSeq();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedTime();
    }

    @Override
    public String component6() {
        return getLocation();
    }

    @Override
    public LocalDateTime component7() {
        return getModifiedTime();
    }

    @Override
    public String component8() {
        return getRemark();
    }

    @Override
    public String component9() {
        return getVaccinationType();
    }

    @Override
    public LocalDate value1() {
        return getDay();
    }

    @Override
    public String value2() {
        return getEntityIdentificationNumber();
    }

    @Override
    public String value3() {
        return getEntityManagementNumber();
    }

    @Override
    public Short value4() {
        return getSeq();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedTime();
    }

    @Override
    public String value6() {
        return getLocation();
    }

    @Override
    public LocalDateTime value7() {
        return getModifiedTime();
    }

    @Override
    public String value8() {
        return getRemark();
    }

    @Override
    public String value9() {
        return getVaccinationType();
    }

    @Override
    public JVaccinationRecord value1(LocalDate value) {
        setDay(value);
        return this;
    }

    @Override
    public JVaccinationRecord value2(String value) {
        setEntityIdentificationNumber(value);
        return this;
    }

    @Override
    public JVaccinationRecord value3(String value) {
        setEntityManagementNumber(value);
        return this;
    }

    @Override
    public JVaccinationRecord value4(Short value) {
        setSeq(value);
        return this;
    }

    @Override
    public JVaccinationRecord value5(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public JVaccinationRecord value6(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public JVaccinationRecord value7(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public JVaccinationRecord value8(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public JVaccinationRecord value9(String value) {
        setVaccinationType(value);
        return this;
    }

    @Override
    public JVaccinationRecord values(LocalDate value1, String value2, String value3, Short value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JVaccinationRecord
     */
    public JVaccinationRecord() {
        super(JVaccination.VACCINATION);
    }

    /**
     * Create a detached, initialised JVaccinationRecord
     */
    public JVaccinationRecord(LocalDate day, String entityIdentificationNumber, String entityManagementNumber, Short seq, LocalDateTime createdTime, String location, LocalDateTime modifiedTime, String remark, String vaccinationType) {
        super(JVaccination.VACCINATION);

        set(0, day);
        set(1, entityIdentificationNumber);
        set(2, entityManagementNumber);
        set(3, seq);
        set(4, createdTime);
        set(5, location);
        set(6, modifiedTime);
        set(7, remark);
        set(8, vaccinationType);
    }
}
