/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain;


import com.skan.farm.domain.tables.JCommonCode;
import com.skan.farm.domain.tables.JHouseKeepingBook;
import com.skan.farm.domain.tables.JPersonalCode;
import com.skan.farm.domain.tables.JSchedule;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>naive-it-farm</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMON_CODE_UPPER_CODE = Indexes0.COMMON_CODE_UPPER_CODE;
    public static final Index HOUSE_KEEPING_BOOK_CATEGORY_CODE = Indexes0.HOUSE_KEEPING_BOOK_CATEGORY_CODE;
    public static final Index PERSONAL_CODE_UPPER_CODE = Indexes0.PERSONAL_CODE_UPPER_CODE;
    public static final Index SCHEDULE_GROUP_NO = Indexes0.SCHEDULE_GROUP_NO;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMMON_CODE_UPPER_CODE = Internal.createIndex("upper_code", JCommonCode.COMMON_CODE, new OrderField[] { JCommonCode.COMMON_CODE.UPPER_CODE }, false);
        public static Index HOUSE_KEEPING_BOOK_CATEGORY_CODE = Internal.createIndex("category_code", JHouseKeepingBook.HOUSE_KEEPING_BOOK, new OrderField[] { JHouseKeepingBook.HOUSE_KEEPING_BOOK.CATEGORY_CODE }, false);
        public static Index PERSONAL_CODE_UPPER_CODE = Internal.createIndex("upper_code", JPersonalCode.PERSONAL_CODE, new OrderField[] { JPersonalCode.PERSONAL_CODE.UPPER_CODE }, false);
        public static Index SCHEDULE_GROUP_NO = Internal.createIndex("group_no", JSchedule.SCHEDULE, new OrderField[] { JSchedule.SCHEDULE.GROUP_NO, JSchedule.SCHEDULE.USER_ID }, false);
    }
}
