/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain;


import com.skan.farm.domain.tables.JAddressDetail;
import com.skan.farm.domain.tables.JAddressManagement;
import com.skan.farm.domain.tables.JAnniversary;
import com.skan.farm.domain.tables.JCattleBuyInformation;
import com.skan.farm.domain.tables.JCommonCode;
import com.skan.farm.domain.tables.JEmail;
import com.skan.farm.domain.tables.JGroupManagement;
import com.skan.farm.domain.tables.JGroupMember;
import com.skan.farm.domain.tables.JHouseKeepingBook;
import com.skan.farm.domain.tables.JLocalBeefManagement;
import com.skan.farm.domain.tables.JPersonalCode;
import com.skan.farm.domain.tables.JPhone;
import com.skan.farm.domain.tables.JSchedule;
import com.skan.farm.domain.tables.JUsers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JNaiveItFarm extends SchemaImpl {

    private static final long serialVersionUID = -1377133876;

    /**
     * The reference instance of <code>naive-it-farm</code>
     */
    public static final JNaiveItFarm NAIVE_IT_FARM = new JNaiveItFarm();

    /**
     * The table <code>naive-it-farm.address_detail</code>.
     */
    public final JAddressDetail ADDRESS_DETAIL = JAddressDetail.ADDRESS_DETAIL;

    /**
     * The table <code>naive-it-farm.address_management</code>.
     */
    public final JAddressManagement ADDRESS_MANAGEMENT = JAddressManagement.ADDRESS_MANAGEMENT;

    /**
     * The table <code>naive-it-farm.anniversary</code>.
     */
    public final JAnniversary ANNIVERSARY = JAnniversary.ANNIVERSARY;

    /**
     * The table <code>naive-it-farm.cattle_buy_information</code>.
     */
    public final JCattleBuyInformation CATTLE_BUY_INFORMATION = JCattleBuyInformation.CATTLE_BUY_INFORMATION;

    /**
     * The table <code>naive-it-farm.common_code</code>.
     */
    public final JCommonCode COMMON_CODE = JCommonCode.COMMON_CODE;

    /**
     * The table <code>naive-it-farm.email</code>.
     */
    public final JEmail EMAIL = JEmail.EMAIL;

    /**
     * The table <code>naive-it-farm.group_management</code>.
     */
    public final JGroupManagement GROUP_MANAGEMENT = JGroupManagement.GROUP_MANAGEMENT;

    /**
     * The table <code>naive-it-farm.group_member</code>.
     */
    public final JGroupMember GROUP_MEMBER = JGroupMember.GROUP_MEMBER;

    /**
     * The table <code>naive-it-farm.house_keeping_book</code>.
     */
    public final JHouseKeepingBook HOUSE_KEEPING_BOOK = JHouseKeepingBook.HOUSE_KEEPING_BOOK;

    /**
     * The table <code>naive-it-farm.local_beef_management</code>.
     */
    public final JLocalBeefManagement LOCAL_BEEF_MANAGEMENT = JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT;

    /**
     * The table <code>naive-it-farm.personal_code</code>.
     */
    public final JPersonalCode PERSONAL_CODE = JPersonalCode.PERSONAL_CODE;

    /**
     * The table <code>naive-it-farm.phone</code>.
     */
    public final JPhone PHONE = JPhone.PHONE;

    /**
     * The table <code>naive-it-farm.schedule</code>.
     */
    public final JSchedule SCHEDULE = JSchedule.SCHEDULE;

    /**
     * The table <code>naive-it-farm.users</code>.
     */
    public final JUsers USERS = JUsers.USERS;

    /**
     * No further instances allowed
     */
    private JNaiveItFarm() {
        super("naive-it-farm", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            JAddressDetail.ADDRESS_DETAIL,
            JAddressManagement.ADDRESS_MANAGEMENT,
            JAnniversary.ANNIVERSARY,
            JCattleBuyInformation.CATTLE_BUY_INFORMATION,
            JCommonCode.COMMON_CODE,
            JEmail.EMAIL,
            JGroupManagement.GROUP_MANAGEMENT,
            JGroupMember.GROUP_MEMBER,
            JHouseKeepingBook.HOUSE_KEEPING_BOOK,
            JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT,
            JPersonalCode.PERSONAL_CODE,
            JPhone.PHONE,
            JSchedule.SCHEDULE,
            JUsers.USERS);
    }
}
