/*
 * This file is generated by jOOQ.
 */
package com.skan.farm.domain;


import com.skan.farm.domain.tables.JCalvesManagement;
import com.skan.farm.domain.tables.JCattleBuyInformation;
import com.skan.farm.domain.tables.JCattleSellStoreInformation;
import com.skan.farm.domain.tables.JCommonCode;
import com.skan.farm.domain.tables.JDiseaseTreatment;
import com.skan.farm.domain.tables.JLocalBeefManagement;
import com.skan.farm.domain.tables.JPersonalCode;
import com.skan.farm.domain.tables.JSchedule;
import com.skan.farm.domain.tables.JUsers;
import com.skan.farm.domain.tables.records.JCalvesManagementRecord;
import com.skan.farm.domain.tables.records.JCattleBuyInformationRecord;
import com.skan.farm.domain.tables.records.JCattleSellStoreInformationRecord;
import com.skan.farm.domain.tables.records.JCommonCodeRecord;
import com.skan.farm.domain.tables.records.JDiseaseTreatmentRecord;
import com.skan.farm.domain.tables.records.JLocalBeefManagementRecord;
import com.skan.farm.domain.tables.records.JPersonalCodeRecord;
import com.skan.farm.domain.tables.records.JScheduleRecord;
import com.skan.farm.domain.tables.records.JUsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>naive-it-farm</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JCalvesManagementRecord> KEY_CALVES_MANAGEMENT_PRIMARY = UniqueKeys0.KEY_CALVES_MANAGEMENT_PRIMARY;
    public static final UniqueKey<JCattleBuyInformationRecord> KEY_CATTLE_BUY_INFORMATION_PRIMARY = UniqueKeys0.KEY_CATTLE_BUY_INFORMATION_PRIMARY;
    public static final UniqueKey<JCattleSellStoreInformationRecord> KEY_CATTLE_SELL_STORE_INFORMATION_PRIMARY = UniqueKeys0.KEY_CATTLE_SELL_STORE_INFORMATION_PRIMARY;
    public static final UniqueKey<JCommonCodeRecord> KEY_COMMON_CODE_PRIMARY = UniqueKeys0.KEY_COMMON_CODE_PRIMARY;
    public static final UniqueKey<JDiseaseTreatmentRecord> KEY_DISEASE_TREATMENT_PRIMARY = UniqueKeys0.KEY_DISEASE_TREATMENT_PRIMARY;
    public static final UniqueKey<JLocalBeefManagementRecord> KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY = UniqueKeys0.KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY;
    public static final UniqueKey<JPersonalCodeRecord> KEY_PERSONAL_CODE_PRIMARY = UniqueKeys0.KEY_PERSONAL_CODE_PRIMARY;
    public static final UniqueKey<JScheduleRecord> KEY_SCHEDULE_PRIMARY = UniqueKeys0.KEY_SCHEDULE_PRIMARY;
    public static final UniqueKey<JUsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<JUsersRecord> KEY_USERS_UK_6EFS5VMCE86YMF5Q7LMVN2UUF = UniqueKeys0.KEY_USERS_UK_6EFS5VMCE86YMF5Q7LMVN2UUF;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<JCalvesManagementRecord, JLocalBeefManagementRecord> FKBTDOIJOBJ7F4J74YLOXQ3X8KA = ForeignKeys0.FKBTDOIJOBJ7F4J74YLOXQ3X8KA;
    public static final ForeignKey<JCalvesManagementRecord, JLocalBeefManagementRecord> FK6EMEBSP37XCSESP63XU8DHGDH = ForeignKeys0.FK6EMEBSP37XCSESP63XU8DHGDH;
    public static final ForeignKey<JCattleBuyInformationRecord, JLocalBeefManagementRecord> FK10C3F92T20D0IDC02YDWEXMP9 = ForeignKeys0.FK10C3F92T20D0IDC02YDWEXMP9;
    public static final ForeignKey<JCattleSellStoreInformationRecord, JLocalBeefManagementRecord> FK7LCCG28LA9RJ67746F63RJHTF = ForeignKeys0.FK7LCCG28LA9RJ67746F63RJHTF;
    public static final ForeignKey<JCommonCodeRecord, JCommonCodeRecord> FKC4P1HKO5VS86OID1LTDGX7S7D = ForeignKeys0.FKC4P1HKO5VS86OID1LTDGX7S7D;
    public static final ForeignKey<JDiseaseTreatmentRecord, JLocalBeefManagementRecord> FKQPKXO8RKFQVR65KXY88EEXRR1 = ForeignKeys0.FKQPKXO8RKFQVR65KXY88EEXRR1;
    public static final ForeignKey<JPersonalCodeRecord, JPersonalCodeRecord> FK1KYMM6VJBNV2QBNEIQEH8KNDN = ForeignKeys0.FK1KYMM6VJBNV2QBNEIQEH8KNDN;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<JCalvesManagementRecord> KEY_CALVES_MANAGEMENT_PRIMARY = Internal.createUniqueKey(JCalvesManagement.CALVES_MANAGEMENT, "KEY_calves_management_PRIMARY", new TableField[] { JCalvesManagement.CALVES_MANAGEMENT.ENTITY_IDENTIFICATION_NUMBER, JCalvesManagement.CALVES_MANAGEMENT.ENTITY_MANAGEMENT_NUMBER, JCalvesManagement.CALVES_MANAGEMENT.SEQ }, true);
        public static final UniqueKey<JCattleBuyInformationRecord> KEY_CATTLE_BUY_INFORMATION_PRIMARY = Internal.createUniqueKey(JCattleBuyInformation.CATTLE_BUY_INFORMATION, "KEY_cattle_buy_information_PRIMARY", new TableField[] { JCattleBuyInformation.CATTLE_BUY_INFORMATION.ENTITY_IDENTIFICATION_NUMBER, JCattleBuyInformation.CATTLE_BUY_INFORMATION.ENTITY_MANAGEMENT_NUMBER }, true);
        public static final UniqueKey<JCattleSellStoreInformationRecord> KEY_CATTLE_SELL_STORE_INFORMATION_PRIMARY = Internal.createUniqueKey(JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION, "KEY_cattle_sell_store_information_PRIMARY", new TableField[] { JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.ENTITY_IDENTIFICATION_NUMBER, JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.ENTITY_MANAGEMENT_NUMBER }, true);
        public static final UniqueKey<JCommonCodeRecord> KEY_COMMON_CODE_PRIMARY = Internal.createUniqueKey(JCommonCode.COMMON_CODE, "KEY_common_code_PRIMARY", new TableField[] { JCommonCode.COMMON_CODE.CODE }, true);
        public static final UniqueKey<JDiseaseTreatmentRecord> KEY_DISEASE_TREATMENT_PRIMARY = Internal.createUniqueKey(JDiseaseTreatment.DISEASE_TREATMENT, "KEY_disease_treatment_PRIMARY", new TableField[] { JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_IDENTIFICATION_NUMBER, JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_MANAGEMENT_NUMBER, JDiseaseTreatment.DISEASE_TREATMENT.SEQ }, true);
        public static final UniqueKey<JLocalBeefManagementRecord> KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY = Internal.createUniqueKey(JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT, "KEY_local_beef_management_PRIMARY", new TableField[] { JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.ENTITY_IDENTIFICATION_NUMBER, JLocalBeefManagement.LOCAL_BEEF_MANAGEMENT.ENTITY_MANAGEMENT_NUMBER }, true);
        public static final UniqueKey<JPersonalCodeRecord> KEY_PERSONAL_CODE_PRIMARY = Internal.createUniqueKey(JPersonalCode.PERSONAL_CODE, "KEY_personal_code_PRIMARY", new TableField[] { JPersonalCode.PERSONAL_CODE.CODE }, true);
        public static final UniqueKey<JScheduleRecord> KEY_SCHEDULE_PRIMARY = Internal.createUniqueKey(JSchedule.SCHEDULE, "KEY_schedule_PRIMARY", new TableField[] { JSchedule.SCHEDULE.UUID }, true);
        public static final UniqueKey<JUsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(JUsers.USERS, "KEY_users_PRIMARY", new TableField[] { JUsers.USERS.UUID }, true);
        public static final UniqueKey<JUsersRecord> KEY_USERS_UK_6EFS5VMCE86YMF5Q7LMVN2UUF = Internal.createUniqueKey(JUsers.USERS, "KEY_users_UK_6efs5vmce86ymf5q7lmvn2uuf", new TableField[] { JUsers.USERS.USER_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<JCalvesManagementRecord, JLocalBeefManagementRecord> FKBTDOIJOBJ7F4J74YLOXQ3X8KA = Internal.createForeignKey(Keys.KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY, JCalvesManagement.CALVES_MANAGEMENT, "FKbtdoijobj7f4j74yloxq3x8ka", new TableField[] { JCalvesManagement.CALVES_MANAGEMENT.ENTITY_IDENTIFICATION_NUMBER, JCalvesManagement.CALVES_MANAGEMENT.ENTITY_MANAGEMENT_NUMBER }, true);
        public static final ForeignKey<JCalvesManagementRecord, JLocalBeefManagementRecord> FK6EMEBSP37XCSESP63XU8DHGDH = Internal.createForeignKey(Keys.KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY, JCalvesManagement.CALVES_MANAGEMENT, "FK6emebsp37xcsesp63xu8dhgdh", new TableField[] { JCalvesManagement.CALVES_MANAGEMENT.ENTITY_IDENTIFICATION_NUMBER_CHILD, JCalvesManagement.CALVES_MANAGEMENT.ENTITY_MANAGEMENT_NUMBER_CHILD }, true);
        public static final ForeignKey<JCattleBuyInformationRecord, JLocalBeefManagementRecord> FK10C3F92T20D0IDC02YDWEXMP9 = Internal.createForeignKey(Keys.KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY, JCattleBuyInformation.CATTLE_BUY_INFORMATION, "FK10c3f92t20d0idc02ydwexmp9", new TableField[] { JCattleBuyInformation.CATTLE_BUY_INFORMATION.ENTITY_IDENTIFICATION_NUMBER, JCattleBuyInformation.CATTLE_BUY_INFORMATION.ENTITY_MANAGEMENT_NUMBER }, true);
        public static final ForeignKey<JCattleSellStoreInformationRecord, JLocalBeefManagementRecord> FK7LCCG28LA9RJ67746F63RJHTF = Internal.createForeignKey(Keys.KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY, JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION, "FK7lccg28la9rj67746f63rjhtf", new TableField[] { JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.ENTITY_IDENTIFICATION_NUMBER, JCattleSellStoreInformation.CATTLE_SELL_STORE_INFORMATION.ENTITY_MANAGEMENT_NUMBER }, true);
        public static final ForeignKey<JCommonCodeRecord, JCommonCodeRecord> FKC4P1HKO5VS86OID1LTDGX7S7D = Internal.createForeignKey(Keys.KEY_COMMON_CODE_PRIMARY, JCommonCode.COMMON_CODE, "FKc4p1hko5vs86oid1ltdgx7s7d", new TableField[] { JCommonCode.COMMON_CODE.UPPER_CODE }, true);
        public static final ForeignKey<JDiseaseTreatmentRecord, JLocalBeefManagementRecord> FKQPKXO8RKFQVR65KXY88EEXRR1 = Internal.createForeignKey(Keys.KEY_LOCAL_BEEF_MANAGEMENT_PRIMARY, JDiseaseTreatment.DISEASE_TREATMENT, "FKqpkxo8rkfqvr65kxy88eexrr1", new TableField[] { JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_IDENTIFICATION_NUMBER, JDiseaseTreatment.DISEASE_TREATMENT.ENTITY_MANAGEMENT_NUMBER }, true);
        public static final ForeignKey<JPersonalCodeRecord, JPersonalCodeRecord> FK1KYMM6VJBNV2QBNEIQEH8KNDN = Internal.createForeignKey(Keys.KEY_PERSONAL_CODE_PRIMARY, JPersonalCode.PERSONAL_CODE, "FK1kymm6vjbnv2qbneiqeh8kndn", new TableField[] { JPersonalCode.PERSONAL_CODE.UPPER_CODE }, true);
    }
}
