package com.skan.farm.model;

import java.io.Serializable;

/**
 * 주소 상세 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AddressDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 주소록 관리. */
	private AddressManagement addressManagement;

	/** 순번. */
	private Long hmAdNo;

	/** 구분. */
	private String hmType;

	/** 주소정보. */
	private String hmAddInfo;


	/**
	 * 생성자.
	 */
	public AddressDetail() {
	}



	/**
	 * 순번을 설정합니다..
	 * 
	 * @param hmAdNo
	 *            순번
	 */
	public void setHmAdNo(Long hmAdNo) {
		this.hmAdNo = hmAdNo;
	}

	/**
	 * 순번을 가져옵니다..
	 * 
	 * @return 순번
	 */
	public Long getHmAdNo() {
		return this.hmAdNo;
	}

	/**
	 * 구분을 설정합니다..
	 * 
	 * @param hmType
	 *            구분
	 */
	public void setHmType(String hmType) {
		this.hmType = hmType;
	}

	/**
	 * 구분을 가져옵니다..
	 * 
	 * @return 구분
	 */
	public String getHmType() {
		return this.hmType;
	}

	/**
	 * 주소정보을 설정합니다..
	 * 
	 * @param hmAddInfo
	 *            주소정보
	 */
	public void setHmAddInfo(String hmAddInfo) {
		this.hmAddInfo = hmAddInfo;
	}

	/**
	 * 주소정보을 가져옵니다..
	 * 
	 * @return 주소정보
	 */
	public String getHmAddInfo() {
		return this.hmAddInfo;
	}

	/**
	 * 주소록 관리을 설정합니다..
	 * 
	 * @param addressManagement
	 *            주소록 관리
	 */
	public void setAddressManagement(AddressManagement addressManagement) {
		this.addressManagement = addressManagement;
	}

	/**
	 * 주소록 관리을 가져옵니다..
	 * 
	 * @return 주소록 관리
	 */
	public AddressManagement getAddressManagement() {
		return this.addressManagement;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addressManagement == null) ? 0 : addressManagement.hashCode());
		result = prime * result + ((hmAdNo == null) ? 0 : hmAdNo.hashCode());
		result = prime * result + ((addressManagement == null) ? 0 : addressManagement.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AddressDetail other = (AddressDetail) obj;
		if (addressManagement == null) {
			if (other.addressManagement != null) {
				return false;
			}
		} else if (!addressManagement.equals(other.addressManagement)) {
			return false;
		}
		if (hmAdNo == null) {
			if (other.hmAdNo != null) {
				return false;
			}
		} else if (!hmAdNo.equals(other.hmAdNo)) {
			return false;
		}
		if (addressManagement == null) {
			if (other.addressManagement != null) {
				return false;
			}
		} else if (!addressManagement.equals(other.addressManagement)) {
			return false;
		}
		return true;
	}

}
