package com.skan.farm.model;

import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * 분만관리(송아지 관리) 모델 클래스.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
@Getter
@Setter
@EqualsAndHashCode
//@Entity
@ToString(exclude = {"localBeefManagement","localBeefManagement2"})
public class CalvesManagement implements Serializable {

    /**
     * serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    @Embeddable
    @Getter@Setter
    @EqualsAndHashCode
    public static class CalvesManagementPK implements Serializable {
        /**
         * 개체관리번호.
         */
        private String entityManagementNumber;

        /**
         * 개체식별번호.
         */
        private String entityIdentificationNumber;

        /**
         * 순번.
         */
        private Short seq;
    }

    @EmbeddedId
    CalvesManagementPK calvesManagementPK;


    /**
     * 수정 회차.
     */
    private Short fertilizationIndex;

    /**
     * 년도.
     */
    private String years;

    /**
     * 수정일자.
     */
    private LocalDateTime fertilizationDate;

    /**
     * 분만예정일.
     */
    private LocalDateTime expectedDateConfinement;

    /**
     * 실제 분만일자.
     */
    private LocalDateTime calvingDate;

    /**
     * 정액번호.
     */
    private Long spermNo;

    /**
     * 특이사항.
     */
    private String nothingSpecial;

    /**
     * 개체식별번호(자식).
     */
    @Column(nullable = false)
    private String entityIdentificationNumberChild;

    /**
     * 개체관리번호(자식).
     */
    @Column(nullable = false)
    private String entityManagementNumberChild;

    /**
     * 한우(암소/수소) 개체관리기록부.
     * 식별 연결
     */
    @MapsId("localBeefManagementPK")
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns({
            @JoinColumn(name = "entityIdentificationNumber", referencedColumnName = "entityIdentificationNumber", insertable = false, updatable = false),
            @JoinColumn(name = "entityManagementNumber", referencedColumnName = "entityManagementNumber", insertable = false, updatable = false),
    })
    private LocalBeefManagement localBeefManagement;

    /**
     * 비식별 연동 키  (FK를 걸기 위함)
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "entityIdentificationNumberChild", referencedColumnName = "entityIdentificationNumber", insertable = false, updatable = false)
    @JoinColumn(name = "entityManagementNumberChild", referencedColumnName = "entityManagementNumber", insertable = false, updatable = false)
    private LocalBeefManagement localBeefManagement2;

    /**
     * 생성자.
     */
    public CalvesManagement() {
    }


}
