package com.skan.farm.model;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDate;

/**
 * 판매지정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Data
public class CattleSellStoreInformation implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;


	@Embeddable
	@Data
	public static class CattleSellStoreInformationPK implements Serializable {
		/**
		 * 개체관리번호.
		 */
		private String entityManagementNumber;

		/**
		 * 개체식별번호.
		 */
		private String entityIdentificationNumber;
	}

	@EmbeddedId
	CattleSellStoreInformationPK cattleSellStoreInformationPK;

	/** 판매처. */
	private String storeName;

	/** 판매/도태일자. */
	private LocalDate sellDate;

	/** 비고. */
	private String sellNote;

	/** 판매 연락처. */
	private String sellPhoneNumber;

	/** 판매가격. */
	private Integer sellingPrice;

	/** 생체중(살아있는생물의무게). */
	private Short liveweight;

	/** 도체중( 도살한 가축의 가죽, 머리, 발목, 내장 따위를 떼어 낸 나머지 몸뚱이의 체중.). */
	private Short dressedWeight;

	/** 등급(1++A, 1++B). */
	private String beefGrade;

	@MapsId("localBeefManagementPK")
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "entityIdentificationNumber", referencedColumnName = "entityIdentificationNumber", insertable = false, updatable = false),
			@JoinColumn(name = "entityManagementNumber", referencedColumnName = "entityManagementNumber", insertable = false, updatable = false),
	})
	/** 한우(암소/수소) 개체관리기록부. */
	private LocalBeefManagement localBeefManagement;

	/**
	 * 생성자.
	 */
	public CattleSellStoreInformation() {
	}


}
