package com.skan.farm.model;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDate;

/**
 * 구입기록 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CattleBuyInformation implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Embeddable
	@Data
	@AllArgsConstructor
	public static class CattleBuyInformationPK implements Serializable {
		/**
		 * 개체관리번호.
		 */
		private String entityManagementNumber;

		/**
		 * 개체식별번호.
		 */
		private String entityIdentificationNumber;

		public CattleBuyInformationPK() {
		}
	}

	@EmbeddedId
	CattleBuyInformationPK cattleBuyInformationPK;

	/** 구입처. */
	private String buyStoreName;

	/** 구입일자. */
	private LocalDate buyDate;

	/** 비고. */
	private String buyNote;

	/** 구입 연락처. */
	private String buyPhoneNumber;

	/** 구입 연락처 전화번호 2. */
	private String buySellPhoneNumber;

	/** 한우(암소/수소) 개체관리기록부. */
	@MapsId("localBeefManagementPK")
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "entityIdentificationNumber", referencedColumnName = "entityIdentificationNumber"),
			@JoinColumn(name = "entityManagementNumber", referencedColumnName = "entityManagementNumber"),
	})
	private LocalBeefManagement localBeefManagement;

}
