package com.skan.farm.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 공통코드 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommonCode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 코드. */
	private String code;

	/** 공통코드. */
	private CommonCode upperCommonCode;

	/** 그룹별 코드 순번. */
	private Long codeSeq;

	/** 코드이름. */
	private String codeName;

	/** 코드 설명. */
	private String codeComment;

	/** 생성일시. */
	private Date createdTime;

	/** 공통코드 목록. */
	private Set<CommonCode> commonCodeSet;

	/**
	 * 생성자.
	 */
	public CommonCode() {
		this.commonCodeSet = new HashSet<CommonCode>();
	}

	/**
	 * 코드을 설정합니다..
	 * 
	 * @param code
	 *            코드
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * 코드을 가져옵니다..
	 * 
	 * @return 코드
	 */
	public String getCode() {
		return this.code;
	}

	/**
	 * 공통코드을 설정합니다..
	 * 
	 * @param upperCommonCode
	 *            공통코드
	 */
	public void setUpperCommonCode(CommonCode upperCommonCode) {
		this.upperCommonCode = upperCommonCode;
	}

	/**
	 * 공통코드을 가져옵니다..
	 * 
	 * @return 공통코드
	 */
	public CommonCode getUpperCommonCode() {
		return this.upperCommonCode;
	}

	/**
	 * 그룹별 코드 순번을 설정합니다..
	 * 
	 * @param codeSeq
	 *            그룹별 코드 순번
	 */
	public void setCodeSeq(Long codeSeq) {
		this.codeSeq = codeSeq;
	}

	/**
	 * 그룹별 코드 순번을 가져옵니다..
	 * 
	 * @return 그룹별 코드 순번
	 */
	public Long getCodeSeq() {
		return this.codeSeq;
	}

	/**
	 * 코드이름을 설정합니다..
	 * 
	 * @param codeName
	 *            코드이름
	 */
	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	/**
	 * 코드이름을 가져옵니다..
	 * 
	 * @return 코드이름
	 */
	public String getCodeName() {
		return this.codeName;
	}

	/**
	 * 코드 설명을 설정합니다..
	 * 
	 * @param codeComment
	 *            코드 설명
	 */
	public void setCodeComment(String codeComment) {
		this.codeComment = codeComment;
	}

	/**
	 * 코드 설명을 가져옵니다..
	 * 
	 * @return 코드 설명
	 */
	public String getCodeComment() {
		return this.codeComment;
	}

	/**
	 * 생성일시을 설정합니다..
	 * 
	 * @param createdTime
	 *            생성일시
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * 생성일시을 가져옵니다..
	 * 
	 * @return 생성일시
	 */
	public Date getCreatedTime() {
		return this.createdTime;
	}

	/**
	 * 공통코드 목록을 설정합니다..
	 * 
	 * @param commonCodeSet
	 *            공통코드 목록
	 */
	public void setCommonCodeSet(Set<CommonCode> commonCodeSet) {
		this.commonCodeSet = commonCodeSet;
	}

	/**
	 * 공통코드를 추가합니다..
	 * 
	 * @param commonCode
	 *            공통코드
	 */
	public void addCommonCode(CommonCode commonCode) {
		this.commonCodeSet.add(commonCode);
	}

	/**
	 * 공통코드 목록을 가져옵니다..
	 * 
	 * @return 공통코드 목록
	 */
	public Set<CommonCode> getCommonCodeSet() {
		return this.commonCodeSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CommonCode other = (CommonCode) obj;
		if (code == null) {
			if (other.code != null) {
				return false;
			}
		} else if (!code.equals(other.code)) {
			return false;
		}
		return true;
	}

}
