package com.skan.farm.model;


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 그룹관리 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GroupManagement implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 그룹번호. */
	private Integer groupNo;

	/** 그룹 이름. */
	private String groupName;

	/** 그룹설명. */
	private String groupDesc;

	/** 그룹 생성일. */
	private Date groupCrtTime;

	/** 그룹멤버 목록. */
	private Set<GroupMember> groupMemberSet;

	/**
	 * 생성자.
	 */
	public GroupManagement() {
		this.groupMemberSet = new HashSet<GroupMember>();
	}

	/**
	 * 그룹번호을 설정합니다..
	 * 
	 * @param groupNo
	 *            그룹번호
	 */
	public void setGroupNo(Integer groupNo) {
		this.groupNo = groupNo;
	}

	/**
	 * 그룹번호을 가져옵니다..
	 * 
	 * @return 그룹번호
	 */
	public Integer getGroupNo() {
		return this.groupNo;
	}

	/**
	 * 그룹 이름을 설정합니다..
	 * 
	 * @param groupName
	 *            그룹 이름
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * 그룹 이름을 가져옵니다..
	 * 
	 * @return 그룹 이름
	 */
	public String getGroupName() {
		return this.groupName;
	}

	/**
	 * 그룹설명을 설정합니다..
	 * 
	 * @param groupDesc
	 *            그룹설명
	 */
	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	/**
	 * 그룹설명을 가져옵니다..
	 * 
	 * @return 그룹설명
	 */
	public String getGroupDesc() {
		return this.groupDesc;
	}

	/**
	 * 그룹 생성일을 설정합니다..
	 * 
	 * @param groupCrtTime
	 *            그룹 생성일
	 */
	public void setGroupCrtTime(Date groupCrtTime) {
		this.groupCrtTime = groupCrtTime;
	}

	/**
	 * 그룹 생성일을 가져옵니다..
	 * 
	 * @return 그룹 생성일
	 */
	public Date getGroupCrtTime() {
		return this.groupCrtTime;
	}

	/**
	 * 그룹멤버 목록을 설정합니다..
	 * 
	 * @param groupMemberSet
	 *            그룹멤버 목록
	 */
	public void setGroupMemberSet(Set<GroupMember> groupMemberSet) {
		this.groupMemberSet = groupMemberSet;
	}

	/**
	 * 그룹멤버를 추가합니다..
	 * 
	 * @param groupMember
	 *            그룹멤버
	 */
	public void addGroupMember(GroupMember groupMember) {
		this.groupMemberSet.add(groupMember);
	}

	/**
	 * 그룹멤버 목록을 가져옵니다..
	 * 
	 * @return 그룹멤버 목록
	 */
	public Set<GroupMember> getGroupMemberSet() {
		return this.groupMemberSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((groupNo == null) ? 0 : groupNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GroupManagement other = (GroupManagement) obj;
		if (groupNo == null) {
			if (other.groupNo != null) {
				return false;
			}
		} else if (!groupNo.equals(other.groupNo)) {
			return false;
		}
		return true;
	}

}
