package com.skan.farm.model;

import lombok.Data;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 한우(암소/수소) 개체관리기록부 모델 클래스.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Data
@ToString(exclude = {"calvesManagementSet", "cattleBuyInformationSet", "cattleSellStoreInformationSet", "diseaseTreatmentSet"})
public class LocalBeefManagement implements Serializable {

    /**
     * serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    @Embeddable
    @Data
    public static class LocalBeefManagementPK implements Serializable {
        /**
         * 개체관리번호.
         */
        private String entityManagementNumber;

        /**
         * 개체식별번호.
         */
        private String entityIdentificationNumber;
    }

    @EmbeddedId
    LocalBeefManagementPK localBeefManagementPK;


    /**
     * 부 번호.
     */
    private String parentPapaNo;

    /**
     * 모 번호.
     */
    private String parentMomNo;

    /**
     * 출생일, 태어난날.
     */
    private Date birthDay;

    /**
     * 입식일.
     */
    private Date enterDate;

    /**
     * 귀표장착일.
     */
    private Date earTagDate;

    /**
     * 거세일.
     */
    private Date castrationDate;

    /**
     * 성별.
     */
    private String gender;

    /**
     * 판매여부.
     */
    private String sellYn;

    /**
     * 생성일시.
     */
    private Date createdTime;

    /**
     * 수정시간.
     */
    private Date modifiedTime;

    /**
     * 분만관리(송아지 관리) 목록.
     */
    @OneToMany(mappedBy = "localBeefManagement", fetch = FetchType.LAZY)
    private Set<CalvesManagement> calvesManagementSet;

    /**
     * 구입기록 목록.
     */
    @OneToMany(mappedBy = "localBeefManagement", fetch = FetchType.LAZY)
    private Set<CattleBuyInformation> cattleBuyInformationSet;

    /**
     * 판매지정보 목록.
     */
    @OneToMany(mappedBy = "localBeefManagement", fetch = FetchType.LAZY)
    private Set<CattleSellStoreInformation> cattleSellStoreInformationSet;

    /**
     * 질병 및 치료 목록.
     */
    @OneToMany(mappedBy = "localBeefManagement", fetch = FetchType.LAZY)
    private Set<DiseaseTreatment> diseaseTreatmentSet;

    /**
     * 생성자.
     */
    public LocalBeefManagement() {
        this.calvesManagementSet = new HashSet<CalvesManagement>();
        this.cattleBuyInformationSet = new HashSet<CattleBuyInformation>();
        this.cattleSellStoreInformationSet = new HashSet<CattleSellStoreInformation>();
        this.diseaseTreatmentSet = new HashSet<DiseaseTreatment>();
    }


}
