package com.skan.farm.model;

import com.skan.farm.code.GenderCode;
import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 한우(암소/수소) 개체관리기록부 모델 클래스.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Data
@ToString(exclude = {"calvesManagementSet", "cattleBuyInformation", "cattleSellStoreInformationSet", "diseaseTreatmentSet"})
@AllArgsConstructor
@Builder
public class LocalBeefManagement implements Serializable {

    /**
     * serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    @Embeddable
    @Data
    @AllArgsConstructor
    public static class LocalBeefManagementPK implements Serializable {
        /**
         * 개체관리번호.
         */
        private String entityManagementNumber;

        /**
         * 개체식별번호.
         */
        private String entityIdentificationNumber;

        public LocalBeefManagementPK() {
        }
    }

    @EmbeddedId
    LocalBeefManagementPK localBeefManagementPK;


    /**
     * 부 번호.
     */
    private String parentPapaNo;

    /**
     * 모 번호.
     */
    private String parentMomNo;

    /**
     * 출생일, 태어난날.
     */
    private LocalDate birthDay;

    /**
     * 입식일.
     */
    private LocalDate enterDate;

    /**
     * 귀표장착일.
     */
    private LocalDate earTagDate;

    /**
     * 거세일.
     */
    private LocalDate castrationDate;

    /**
     * 성별.
     */
    @Enumerated(EnumType.STRING)
    private GenderCode gender;

    /**
     * 판매여부.
     */
    private String sellYn;

    /**
     * 생성일시.
     */
    private Date createdTime;

    /**
     * 수정시간.
     */
    private Date modifiedTime;

    /**
     * 분만관리(송아지 관리) 목록.
     */
    @OneToMany(mappedBy = "localBeefManagement", fetch = FetchType.LAZY)
    private Set<CalvesManagement> calvesManagementSet;

    /**
     * 구입기록 목록.
     */
    @OneToOne(mappedBy = "localBeefManagement", fetch = FetchType.LAZY, optional = false, cascade = CascadeType.ALL)
    private CattleBuyInformation cattleBuyInformation;

    /**
     * 판매지정보 목록.
     */
    @OneToMany(mappedBy = "localBeefManagement", fetch = FetchType.LAZY)
    private Set<CattleSellStoreInformation> cattleSellStoreInformationSet;

    /**
     * 질병 및 치료 목록.
     */
    @OneToMany(mappedBy = "localBeefManagement", fetch = FetchType.LAZY)
    private Set<DiseaseTreatment> diseaseTreatmentSet;

    /**
     * 생성자.
     */
    public LocalBeefManagement() {
        this.calvesManagementSet = new HashSet<CalvesManagement>();
        //this.cattleBuyInformation = new CattleBuyInformation();
        this.cattleSellStoreInformationSet = new HashSet<CattleSellStoreInformation>();
        this.diseaseTreatmentSet = new HashSet<DiseaseTreatment>();
    }


}
