package com.skan.farm.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 개인코드 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PersonalCode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 코드. */
	private String code;

	/** 개인코드. */
	private PersonalCode upperPersonalCode;

	/** 사용자 아이디. */
	private String userId;

	/** 순서. */
	private Integer codeSeq;

	/** 코드명. */
	private String codeName;

	/** 코드 상세. */
	private String codeComments;

	/** 생성일시. */
	private Date createdTime;

	/** 가계부(house_keeping_book) 목록. */
	private Set<HouseKeepingBook> houseKeepingBookSet;

	/** 개인코드 목록. */
	private Set<PersonalCode> personalCodeSet;

	/**
	 * 생성자.
	 */
	public PersonalCode() {
		this.houseKeepingBookSet = new HashSet<HouseKeepingBook>();
		this.personalCodeSet = new HashSet<PersonalCode>();
	}

	/**
	 * 코드을 설정합니다..
	 * 
	 * @param code
	 *            코드
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * 코드을 가져옵니다..
	 * 
	 * @return 코드
	 */
	public String getCode() {
		return this.code;
	}

	/**
	 * 개인코드을 설정합니다..
	 * 
	 * @param upperPersonalCode
	 *            개인코드
	 */
	public void setUpperPersonalCode(PersonalCode upperPersonalCode) {
		this.upperPersonalCode = upperPersonalCode;
	}

	/**
	 * 개인코드을 가져옵니다..
	 * 
	 * @return 개인코드
	 */
	public PersonalCode getUpperPersonalCode() {
		return this.upperPersonalCode;
	}

	/**
	 * 사용자 아이디을 설정합니다..
	 * 
	 * @param userId
	 *            사용자 아이디
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * 사용자 아이디을 가져옵니다..
	 * 
	 * @return 사용자 아이디
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * 순서을 설정합니다..
	 * 
	 * @param codeSeq
	 *            순서
	 */
	public void setCodeSeq(Integer codeSeq) {
		this.codeSeq = codeSeq;
	}

	/**
	 * 순서을 가져옵니다..
	 * 
	 * @return 순서
	 */
	public Integer getCodeSeq() {
		return this.codeSeq;
	}

	/**
	 * 코드명을 설정합니다..
	 * 
	 * @param codeName
	 *            코드명
	 */
	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	/**
	 * 코드명을 가져옵니다..
	 * 
	 * @return 코드명
	 */
	public String getCodeName() {
		return this.codeName;
	}

	/**
	 * 코드 상세을 설정합니다..
	 * 
	 * @param codeComments
	 *            코드 상세
	 */
	public void setCodeComments(String codeComments) {
		this.codeComments = codeComments;
	}

	/**
	 * 코드 상세을 가져옵니다..
	 * 
	 * @return 코드 상세
	 */
	public String getCodeComments() {
		return this.codeComments;
	}

	/**
	 * 생성일시을 설정합니다..
	 * 
	 * @param createdTime
	 *            생성일시
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * 생성일시을 가져옵니다..
	 * 
	 * @return 생성일시
	 */
	public Date getCreatedTime() {
		return this.createdTime;
	}

	/**
	 * 가계부(house_keeping_book) 목록을 설정합니다..
	 * 
	 * @param houseKeepingBookSet
	 *            가계부(house_keeping_book) 목록
	 */
	public void setHouseKeepingBookSet(Set<HouseKeepingBook> houseKeepingBookSet) {
		this.houseKeepingBookSet = houseKeepingBookSet;
	}

	/**
	 * 가계부(house_keeping_book)를 추가합니다..
	 * 
	 * @param houseKeepingBook
	 *            가계부(house_keeping_book)
	 */
	public void addHouseKeepingBook(HouseKeepingBook houseKeepingBook) {
		this.houseKeepingBookSet.add(houseKeepingBook);
	}

	/**
	 * 가계부(house_keeping_book) 목록을 가져옵니다..
	 * 
	 * @return 가계부(house_keeping_book) 목록
	 */
	public Set<HouseKeepingBook> getHouseKeepingBookSet() {
		return this.houseKeepingBookSet;
	}

	/**
	 * 개인코드 목록을 설정합니다..
	 * 
	 * @param personalCodeSet
	 *            개인코드 목록
	 */
	public void setPersonalCodeSet(Set<PersonalCode> personalCodeSet) {
		this.personalCodeSet = personalCodeSet;
	}

	/**
	 * 개인코드를 추가합니다..
	 * 
	 * @param personalCode
	 *            개인코드
	 */
	public void addPersonalCode(PersonalCode personalCode) {
		this.personalCodeSet.add(personalCode);
	}

	/**
	 * 개인코드 목록을 가져옵니다..
	 * 
	 * @return 개인코드 목록
	 */
	public Set<PersonalCode> getPersonalCodeSet() {
		return this.personalCodeSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PersonalCode other = (PersonalCode) obj;
		if (code == null) {
			if (other.code != null) {
				return false;
			}
		} else if (!code.equals(other.code)) {
			return false;
		}
		return true;
	}

}
