package com.skan.farm.model;

import lombok.Data;
import lombok.ToString;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * 개인코드 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Data
@ToString (exclude = "personalCodes")
public class PersonalCode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 코드. */
	@Id
	private String code;

	/** 사용자 아이디. */
	@NotNull(message = "사용자 아이디는 필수 입니다.")
	@Column(nullable = false)
	private String userId;

	/** 순서. */
	private Integer codeSeq;

	/** 코드명. */
	private String codeName;

	/** 코드 상세. */
	private String codeComments;

	/** 생성일시. */
	private Date createdTime;

	/**개인코드. */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "upperCode", referencedColumnName = "code")
	private PersonalCode parentCode;

	/** 개인코드 목록. */
	@OneToMany(mappedBy = "parentCode", fetch = FetchType.LAZY)
	private List<PersonalCode> personalCodes;

	public PersonalCode() {
	}

}
