package com.skan.farm.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 일정관리 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Schedule implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 일정관리번호. */
	private Long schMgtNo;

	/** 같은날의 순번. */
	private Long schSeq;

	/** 제목. */
	private String schSubject;

	/** 내용. */
	private String schContent;

	/** 기준날짜. */
	private String stdDate;

	/** 오늘 날씨. */
	private String todayWeatherCode;

	/** 최저온도(영상/영하구분). */
	private String minDegreespointCode;

	/** 최고온도(영상/영하)구분. */
	private String maxDegreespointCode;

	/** 최저 기온. */
	private Long minTemperature;

	/** 최고온도. */
	private Long maxTemperature;

	/** 생성시간. */
	private Date createTime;

	/** 수정시간. */
	private Date modifyTime;

	/** 공개 여부. */
	private String publicYn;

	/** 그룹관리. */
	private GroupManagement groupManagement;

	/** 그룹멤버. */
	private GroupMember groupMember;

	/**
	 * 생성자.
	 */
	public Schedule() {
	}

	/**
	 * 일정관리번호을 설정합니다..
	 * 
	 * @param schMgtNo
	 *            일정관리번호
	 */
	public void setSchMgtNo(Long schMgtNo) {
		this.schMgtNo = schMgtNo;
	}

	/**
	 * 일정관리번호을 가져옵니다..
	 * 
	 * @return 일정관리번호
	 */
	public Long getSchMgtNo() {
		return this.schMgtNo;
	}

	/**
	 * 같은날의 순번을 설정합니다..
	 * 
	 * @param schSeq
	 *            같은날의 순번
	 */
	public void setSchSeq(Long schSeq) {
		this.schSeq = schSeq;
	}

	/**
	 * 같은날의 순번을 가져옵니다..
	 * 
	 * @return 같은날의 순번
	 */
	public Long getSchSeq() {
		return this.schSeq;
	}

	/**
	 * 제목을 설정합니다..
	 * 
	 * @param schSubject
	 *            제목
	 */
	public void setSchSubject(String schSubject) {
		this.schSubject = schSubject;
	}

	/**
	 * 제목을 가져옵니다..
	 * 
	 * @return 제목
	 */
	public String getSchSubject() {
		return this.schSubject;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param schContent
	 *            내용
	 */
	public void setSchContent(String schContent) {
		this.schContent = schContent;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getSchContent() {
		return this.schContent;
	}

	/**
	 * 기준날짜을 설정합니다..
	 * 
	 * @param stdDate
	 *            기준날짜
	 */
	public void setStdDate(String stdDate) {
		this.stdDate = stdDate;
	}

	/**
	 * 기준날짜을 가져옵니다..
	 * 
	 * @return 기준날짜
	 */
	public String getStdDate() {
		return this.stdDate;
	}

	/**
	 * 오늘 날씨을 설정합니다..
	 * 
	 * @param todayWeatherCode
	 *            오늘 날씨
	 */
	public void setTodayWeatherCode(String todayWeatherCode) {
		this.todayWeatherCode = todayWeatherCode;
	}

	/**
	 * 오늘 날씨을 가져옵니다..
	 * 
	 * @return 오늘 날씨
	 */
	public String getTodayWeatherCode() {
		return this.todayWeatherCode;
	}

	/**
	 * 최저온도(영상/영하구분)을 설정합니다..
	 * 
	 * @param minDegreespointCode
	 *            최저온도(영상/영하구분)
	 */
	public void setMinDegreespointCode(String minDegreespointCode) {
		this.minDegreespointCode = minDegreespointCode;
	}

	/**
	 * 최저온도(영상/영하구분)을 가져옵니다..
	 * 
	 * @return 최저온도(영상/영하구분)
	 */
	public String getMinDegreespointCode() {
		return this.minDegreespointCode;
	}

	/**
	 * 최고온도(영상/영하)구분을 설정합니다..
	 * 
	 * @param maxDegreespointCode
	 *            최고온도(영상/영하)구분
	 */
	public void setMaxDegreespointCode(String maxDegreespointCode) {
		this.maxDegreespointCode = maxDegreespointCode;
	}

	/**
	 * 최고온도(영상/영하)구분을 가져옵니다..
	 * 
	 * @return 최고온도(영상/영하)구분
	 */
	public String getMaxDegreespointCode() {
		return this.maxDegreespointCode;
	}

	/**
	 * 최저 기온을 설정합니다..
	 * 
	 * @param minTemperature
	 *            최저 기온
	 */
	public void setMinTemperature(Long minTemperature) {
		this.minTemperature = minTemperature;
	}

	/**
	 * 최저 기온을 가져옵니다..
	 * 
	 * @return 최저 기온
	 */
	public Long getMinTemperature() {
		return this.minTemperature;
	}

	/**
	 * 최고온도을 설정합니다..
	 * 
	 * @param maxTemperature
	 *            최고온도
	 */
	public void setMaxTemperature(Long maxTemperature) {
		this.maxTemperature = maxTemperature;
	}

	/**
	 * 최고온도을 가져옵니다..
	 * 
	 * @return 최고온도
	 */
	public Long getMaxTemperature() {
		return this.maxTemperature;
	}

	/**
	 * 생성시간을 설정합니다..
	 * 
	 * @param createTime
	 *            생성시간
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * 생성시간을 가져옵니다..
	 * 
	 * @return 생성시간
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * 수정시간을 설정합니다..
	 * 
	 * @param modifyTime
	 *            수정시간
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * 수정시간을 가져옵니다..
	 * 
	 * @return 수정시간
	 */
	public Date getModifyTime() {
		return this.modifyTime;
	}

	/**
	 * 공개 여부을 설정합니다..
	 * 
	 * @param publicYn
	 *            공개 여부
	 */
	public void setPublicYn(String publicYn) {
		this.publicYn = publicYn;
	}

	/**
	 * 공개 여부을 가져옵니다..
	 * 
	 * @return 공개 여부
	 */
	public String getPublicYn() {
		return this.publicYn;
	}

	/**
	 * 그룹관리을 설정합니다..
	 * 
	 * @param groupManagement
	 *            그룹관리
	 */
	public void setGroupManagement(GroupManagement groupManagement) {
		this.groupManagement = groupManagement;
	}

	/**
	 * 그룹관리을 가져옵니다..
	 * 
	 * @return 그룹관리
	 */
	public GroupManagement getGroupManagement() {
		return this.groupManagement;
	}

	/**
	 * 그룹멤버을 설정합니다..
	 * 
	 * @param groupMember
	 *            그룹멤버
	 */
	public void setGroupMember(GroupMember groupMember) {
		this.groupMember = groupMember;
	}

	/**
	 * 그룹멤버을 가져옵니다..
	 * 
	 * @return 그룹멤버
	 */
	public GroupMember getGroupMember() {
		return this.groupMember;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((schMgtNo == null) ? 0 : schMgtNo.hashCode());
		result = prime * result + ((schSeq == null) ? 0 : schSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Schedule other = (Schedule) obj;
		if (schMgtNo == null) {
			if (other.schMgtNo != null) {
				return false;
			}
		} else if (!schMgtNo.equals(other.schMgtNo)) {
			return false;
		}
		if (schSeq == null) {
			if (other.schSeq != null) {
				return false;
			}
		} else if (!schSeq.equals(other.schSeq)) {
			return false;
		}
		return true;
	}

}
